<a href="https://colab.research.google.com/github/esradag/pytorch-derin-ogrenme/blob/main/00_PytorchTemelleri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Temelleri

## PyTorch Nedir?

[PyTorch](https://pytorch.org/), açık kaynaklı bir makine öğrenimi ve derin öğrenme framework'üdür.

## PyTorch Ne İçin Kullanılır?

PyTorch, verileri işlemek ve Python kodu kullanarak makine öğrenimi algoritmaları yazmak için kullanılır.

## Kimler PyTorch Kullanıyor?

Dünyanın en büyük teknoloji şirketlerinden [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/), Tesla ve Microsoft gibi firmalar ile [OpenAI](https://openai.com/blog/openai-pytorch/) gibi yapay zeka araştırma şirketleri, araştırmalarını desteklemek ve makine öğrenimini ürünlerine entegre etmek için PyTorch kullanıyor.

![endüstri ve araştırmada kullanılan pytorch](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

Örneğin, Tesla'nın yapay zeka başkanı Andrej Karpathy, Tesla'nın otonom sürüş bilgisayarlı görü modellerini nasıl PyTorch ile geliştirdiklerini [PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE) ve [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904) etkinliklerinde anlatmıştır.

PyTorch, ayrıca tarım gibi farklı sektörlerde de [traktörlerde bilgisayarlı görü](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1) uygulamalarını desteklemek için kullanılıyor.

## Neden PyTorch Kullanmalıyız?

Makine öğrenimi araştırmacıları PyTorch kullanmayı seviyor. Şubat 2022 itibarıyla PyTorch, makine öğrenimi araştırma makalelerini ve kodlarını takip eden [Papers With Code](https://paperswithcode.com/trends) sitesinde en çok kullanılan derin öğrenme framework'ü olmuştur.

PyTorch ayrıca GPU hızlandırma (kodunuzu daha hızlı çalıştırma) gibi birçok işlemi arka planda yönetir.

Bu sayede veri işleme ve algoritma yazmaya odaklanabilir ve PyTorch kodunuzun hızlı çalışmasını sağlar.

Tesla ve Meta (Facebook) gibi şirketler yüzlerce uygulamayı desteklemek, binlerce aracı sürmek ve milyarlarca insana içerik sunmak için PyTorch kullanıyorsa, geliştirme açısından oldukça güçlü bir araç olduğu açıktır.

## Bu Modülde Neler Öğreneceğiz?

Bu kurs farklı bölümlere (notebook'lara) ayrılmıştır.

Her notebook PyTorch içindeki önemli fikirleri ve kavramları kapsar.

Sonraki notebook'lar önceki bilgilerin üzerine inşa edilir (numaralandırma 00'dan başlar, 01, 02 şeklinde devam eder).

Bu notebook, makine öğrenimi ve derin öğrenmenin temel yapı taşı olan tensörleri ele alır.

Özellikle şu konuları kapsayacağız:

| **Konu** | **İçerik** |
| ----- | ----- |
| **Tensörlere Giriş** | Tensörler, makine öğrenimi ve derin öğrenmenin temel yapı taşlarıdır. |
| **Tensör Oluşturma** | Tensörler, görüntüler, kelimeler, sayı tabloları gibi birçok veri türünü temsil edebilir. |
| **Tensörlerden Bilgi Alma** | Bir tensöre bilgi koyabiliyorsanız, o bilgiyi çıkarmak da isteyeceksiniz. |
| **Tensörleri Manipüle Etme** | Makine öğrenimi algoritmaları (örneğin sinir ağları), tensörleri toplama, çarpma ve birleştirme gibi farklı şekillerde manipüle etmeyi içerir. |
| **Tensör Şekilleriyle Çalışma** | Makine öğreniminde en sık karşılaşılan sorunlardan biri, yanlış şekilli tensörleri birbiriyle karıştırmaktır. |
| **Tensörlerde İndeksleme** | Python listesi veya NumPy dizisi üzerinde indeksleme yaptıysanız, tensörlerde de benzer bir mantık vardır fakat çok daha fazla boyuta sahip olabilirler. |
| **PyTorch Tensörleri ve NumPy Karışımı** | PyTorch tensörlerle ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)), NumPy ise dizilerle ([`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)) çalışır. Bazen bunları birleştirmek isteyebilirsiniz. |
| **Tekrarlanabilirlik (Reproducibility)** | Makine öğrenimi oldukça deneysel bir alandır ve çalışması için çok fazla *rastgelelik* kullanır, bazen bu *rastgeleliğin* o kadar rastgele olmamasını isteyebilirsiniz. |
| **GPU Üzerinde Tensör Çalıştırma** | GPU'lar (Grafik İşlem Birimleri) kodunuzu hızlandırır, PyTorch ise kodunuzu GPU'da çalıştırmayı kolaylaştırır. |

## Nereden Yardım Alabilirsiniz?

Bu kursun tüm materyallerine [GitHub üzerinden ulaşabilirsiniz](https://github.com/mrdbourke/pytorch-deep-learning).

Bir sorunla karşılaşırsanız, [Tartışmalar sayfasında](https://github.com/mrdbourke/pytorch-deep-learning/discussions) soru sorabilirsiniz.

Ayrıca [PyTorch geliştirici forumları](https://discuss.pytorch.org/) da PyTorch hakkında her şey için çok yardımcı bir kaynaktır.


#PyTorch'u İçe Aktarma
> **Not:** Bu kodu çalıştırmadan önce, [PyTorch kurulum adımlarını ] (https://pytorch.org/get-started/locally/)  tamamlamış olmanız gerekir.
> Ancak, **Google Colab kullanıyorsanız **herhangi bir ek kurulum yapmanıza gerek yoktur çünkü PyTorch ve diğer gerekli kütüphaneler Colab'de önceden yüklüdür.

PyTorch'u içe aktararak ve kullanılan sürümü kontrol ederek başlayalım:

In [1]:
import torch
torch.__version__

'2.5.1+cu121'

## Tensörlere Giriş

Artık PyTorch'u içe aktardığımıza göre, tensörleri öğrenme zamanı.

Tensörler, makine öğreniminin temel yapı taşıdır.

Görevleri, verileri sayısal bir şekilde temsil etmektir.

Örneğin, bir resmi `[3, 224, 224]` şeklinde bir tensörle temsil edebilirsiniz. Bu, `[renk_kanalları, yükseklik, genişlik]` anlamına gelir. Yani bu görüntüde `3` renk kanalı (kırmızı, yeşil, mavi), `224` piksel yükseklik ve `224` piksel genişlik vardır.

![girdi görüntüsünden tensör temsilini gösteren örnek, görüntü 3 renk kanalına ve yükseklik ve genişliği temsil eden sayılara ayrılıyor](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

Tensör dilinde (tensörleri tanımlamak için kullanılan dil), bu tensör üç boyuta sahiptir: biri `renk_kanalları`, biri `yükseklik` ve biri de `genişlik` için.

Ama kendimizi fazla ileriye taşıyoruz.

Haydi, tensörleri kodlayarak daha yakından öğrenelim.


### Tensör Oluşturma

PyTorch, tensörleri çok sever. Öyle ki, [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) sınıfına özel bir dökümantasyon sayfası bile var.

İlk ödeviniz, [10 dakika boyunca `torch.Tensor` dökümantasyonunu okumak](https://pytorch.org/docs/stable/tensors.html). Ama bunu daha sonra da yapabilirsiniz.

Haydi kod yazalım.

İlk oluşturacağımız şey bir **skaler** olacak.

Skaler, tek bir sayıdır ve tensör dilinde sıfır boyutlu (0D) bir tensördür.

> **Not:** Bu kursta sıkça karşılaşacağınız bir yaklaşım olacak. Spesifik kodlar yazmaya odaklanacağız. Ancak zaman zaman PyTorch dökümantasyonunu okuyup anlamanızı gerektiren alıştırmalar vereceğim. Çünkü bu kursu bitirdiğinizde daha fazlasını öğrenmek isteyeceğinizden eminim. Ve dökümantasyon, sık sık başvuracağınız bir kaynak olacak.


In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

### Tensörlerin Boyutlarını Kontrol Etme

Yukarıda ekrana **`tensor(7)`** çıktısını gördünüz mü?  

Bu, **scalar** tek bir sayı olmasına rağmen, PyTorch'ta **`torch.Tensor`** türünde olduğunu gösterir.

Bir tensörün boyutunu kontrol etmek için **`.ndim`** özelliğini kullanabiliriz.


In [3]:
scalar.ndim

0

Peki, tensörden bir sayıyı nasıl alabiliriz?

Yani, `torch.Tensor` türünden bir Python tam sayısına nasıl dönüştürebiliriz?

Bunu yapmak için `item()` metodunu kullanabiliriz.


In [4]:
# Bir tensör içindeki Python sayısını al (sadece tek elemanlı tensörlerde çalışır)
scalar.item()


7

Tamam, şimdi bir **vektör** görelim.

Bir vektör, tek boyutlu bir tensördür ancak birçok sayı içerebilir.

Örneğin, evinizdeki `[yatak odası, banyo]` bilgisini `[3, 2]` vektörüyle tanımlayabilirsiniz. Veya `[yatak odası, banyo, otopark]` bilgisini `[3, 2, 2]` vektörüyle ifade edebilirsiniz.

Buradaki önemli nokta, bir vektörün (ve tensörlerin) neyi temsil edebileceği konusunda esnek olmasıdır.


In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Harika, `vector` artık iki adet 7 içeriyor, en sevdiğim sayı.

Peki, sence bu vektör kaç boyutlu olacak?


In [6]:
# Vektörün boyut sayısını kontrol et
vector.ndim


1

Hmm, bu garip, `vector` iki sayı içeriyor ama sadece tek bir boyuta sahip.

Sana küçük bir ipucu vereyim.

PyTorch'ta bir tensörün kaç boyutu olduğunu, dışındaki köşeli parantezlerin (`[`) sayısına bakarak anlayabilirsin ve sadece bir tarafı sayman yeterlidir.

`vector` kaç köşeli paranteze sahip?

Tensörler için bir diğer önemli kavram ise `shape` (şekil) özelliğidir. Shape, tensör içindeki elemanların nasıl düzenlendiğini gösterir.

Şimdi `vector`'ün şeklini kontrol edelim.


In [7]:
# Vektörün şeklini kontrol etme
vector.shape

torch.Size([2])

Yukarıdaki çıktı `torch.Size([2])` döndürür, bu da vektörümüzün `[2]` şeklinde olduğunu gösterir. Bunun nedeni, köşeli parantezler içine iki eleman yerleştirmiş olmamızdır (`[7, 7]`).

Şimdi bir **matris** görelim.


In [8]:

# Matris (2D tensör) oluşturma
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Vay canına! Daha fazla sayı! Matrisler, vektörler kadar esnektir ancak fazladan bir boyuta sahiptirler.


In [9]:
# Matrisin boyut sayısını kontrol etme
MATRIX.ndim

2

`MATRIX` iki boyuta sahip (Bir tarafındaki dış köşeli parantezleri saydın mı?).

Sence `shape` (şekil) değeri ne olacak?


In [10]:
# Matrisin şeklini kontrol etme
MATRIX.shape

torch.Size([2, 2])

Çıktı olarak `torch.Size([2, 2])` alıyoruz çünkü `MATRIX` iki eleman derinliğinde ve iki eleman genişliğinde.

Şimdi bir **tensör** oluşturalım!


In [11]:
# 3 boyutlu bir tensör oluşturma
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

# Tensörü yazdırma
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


Vay canına! Ne kadar güzel bir tensör.

Tensörlerin neredeyse her şeyi temsil edebileceğini vurgulamak istiyorum.

Az önce oluşturduğumuz tensör, bir biftek ve badem ezmesi mağazasının satış rakamlarını temsil edebilir (en sevdiğim iki yiyecekten biri).

![Google Sheets'te haftanın günleri, biftek satışları ve badem ezmesi satışlarını gösteren basit bir tensör](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

Sence bu tensör kaç boyutludur? (ipucu: köşeli parantez sayma yöntemini kullan)


In [12]:
# TENSOR değişkeninin boyut sayısını kontrol etme
TENSOR.ndim

3

Peki ya tensörün şekli (shape) nasıl?

In [13]:
# TENSOR değişkeninin şeklini (boyutlarının düzenini) kontrol etme
TENSOR.shape

torch.Size([1, 3, 3])

Tamam, çıktı olarak `torch.Size([1, 3, 3])` alıyoruz.

Boyutlar dıştan içe doğru sıralanır.

Bu, 3x3'lük 1 adet boyut olduğu anlamına gelir.

![Farklı tensör boyutlarına örnek](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Not:** `scalar` ve `vector` için küçük harf, `MATRIX` ve `TENSOR` için büyük harf kullandığımı fark etmiş olabilirsiniz. Bu bilinçli bir tercih. Pratikte, skalerler ve vektörler genellikle küçük harflerle (`y`, `a`) gösterilir. Matrisler ve tensörler ise büyük harflerle (`X`, `W`) gösterilir.
>
> Ayrıca matris ve tensör terimlerinin bazen birbirinin yerine kullanıldığını da görebilirsiniz. Bu oldukça yaygındır. PyTorch'ta çoğunlukla `torch.Tensor` ile çalıştığınız için tensör terimi kullanılır, ancak içeriğin şekli ve boyutları ne olduğunu belirler.

### Özetleyelim

| **Adı**   | **Nedir?**                                    | **Boyut Sayısı**              | **Genellikle Kullanımı (Örnek)** |
|-----------|-----------------------------------------------|------------------------------|----------------------------------|
| **scalar** | Tek bir sayı                                  | 0                            | Küçük harf (`a`)                 |
| **vector** | Yönü olan bir sayı (örneğin rüzgar hızı) veya birden fazla sayı | 1                            | Küçük harf (`y`)                 |
| **matrix** | 2 boyutlu sayı dizisi                        | 2                            | Büyük harf (`Q`)                 |
| **tensor** | n-boyutlu sayı dizisi                        | Herhangi bir boyut (0: skaler, 1: vektör) | Büyük harf (`X`)                 |

![Skaler, vektör, matris ve tensör örnekleri](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)


### 🎲 Rastgele Tensörler (Random Tensors)

Daha önce tensörlerin verileri temsil ettiğini öğrendik.  
Makine öğrenimi modelleri (özellikle **sinir ağları**) bu tensörleri işleyerek içindeki kalıpları ve ilişkileri keşfeder.

Ancak, PyTorch ile makine öğrenimi modeli geliştirirken, tensörleri elle oluşturmak (şu ana kadar yaptığımız gibi) oldukça nadir bir durumdur.

---

### 🔄 **Makine Öğreniminde Rastgele Tensörlerin Önemi**

Makine öğrenimi modelleri genellikle başlangıçta rastgele sayılarla doldurulmuş büyük tensörlerle başlar.  
Model, bu rastgele sayıları veriyi işlerken günceller ve daha iyi tahminler yapmayı öğrenir.

Bu süreci şu şekilde özetleyebiliriz:

`Rastgele sayılarla başla → Veriye bak → Sayıları güncelle → Veriye tekrar bak → Sayıları güncelle...`

📌 **Veri bilimcisi** olarak, modelin:  
- **Başlangıç değerlerini (initialization)** nasıl belirleyeceğini,  
- **Veriyi (representation)** nasıl işleyeceğini ve  
- **Sayıları (optimization)** nasıl güncelleyeceğini kontrol edebilirsiniz.

Bu adımları ilerleyen bölümlerde uygulamalı olarak inceleyeceğiz.  
Şimdilik, rastgele sayı içeren tensörleri nasıl oluşturacağımıza bakalım.

---

### 📝 **Rastgele Tensör Oluşturma**

Rastgele sayı içeren tensörleri oluşturmak için [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) fonksiyonunu kullanabiliriz.  
Bu fonksiyon, **0 ile 1** arasında rastgele sayı üreten bir tensör oluşturur.



In [14]:
# (3, 4) boyutunda rastgele sayı içeren bir tensör oluşturma
random_tensor = torch.rand(size=(3, 4))

# Tensörü ve veri tipini yazdırma
random_tensor, random_tensor.dtype

(tensor([[0.5246, 0.4837, 0.5311, 0.3527],
         [0.5622, 0.5908, 0.8572, 0.4340],
         [0.4462, 0.6054, 0.7701, 0.0760]]),
 torch.float32)

`torch.rand()` fonksiyonunun esnekliği, `size` parametresini istediğimiz gibi ayarlayabilmemizdir.

Örneğin, yaygın bir görüntü boyutu olan `[224, 224, 3]` şeklinde ( `[yükseklik, genişlik, renk_kanalları]` ) rastgele bir tensör oluşturmak istersek:


In [15]:
# (224, 224, 3) boyutunda rastgele sayı içeren bir tensör oluşturma
random_image_size_tensor = torch.rand(size=(224, 224, 3))

# Tensörün şeklini (shape) ve boyut sayısını (ndim) kontrol etme
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Sıfırlar ve Birler(Zeros and ones)

Bazen tensörleri sadece sıfır veya birlerle doldurmak isteyebilirsin.

Bu durum genellikle maskeleme işlemlerinde kullanılır (bir tensördeki bazı değerleri sıfırlarla maskeleyerek modelin o değerleri öğrenmemesini sağlamak gibi).

Şimdi, [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html) kullanarak sıfırlarla dolu bir tensör oluşturalım.

Yine, burada `size` parametresi önem kazanıyor.


In [16]:
# (3, 4) boyutunda sıfırlardan oluşan bir tensör oluşturma
zeros = torch.zeros(size=(3, 4))

# Tensörü ve veri tipini yazdırma
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Aynı şekilde, tüm elemanları bir olan bir tensör oluşturmak için [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html) fonksiyonunu kullanabiliriz.


In [17]:
# (3, 4) boyutunda birlerden oluşan bir tensör oluşturma
ones = torch.ones(size=(3, 4))

# Tensörü ve veri tipini yazdırma
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Aralık ve Benzer Tensörler Oluşturma

Bazen 1'den 10'a veya 0'dan 100'e kadar bir sayı aralığı oluşturmak isteyebilirsin.

Bunu yapmak için `torch.arange(start, end, step)` fonksiyonunu kullanabilirsin.

Burada:
* `start` = aralığın başlangıç değeri (örn. 0)  
* `end` = aralığın bitiş değeri (örn. 10)  
* `step` = her değerin arasındaki adım sayısı (örn. 1)  

> **Not:** Python'da bir aralık oluşturmak için `range()` fonksiyonunu kullanabilirsin. Ancak PyTorch'ta `torch.range()` artık kullanılmıyor ve gelecekte hata verebilir.


In [18]:
# ⚠️ Dikkat: torch.range() kullanımdan kaldırılmıştır (deprecated)
zero_to_ten_deprecated = torch.range(0, 10)  # Bu kullanım gelecekte hata verebilir!

# ✅ Doğru kullanım: torch.arange() ile 0'dan 10'a kadar bir tensör oluşturma
zero_to_ten = torch.arange(start=0, end=10, step=1)

# Tensörü yazdırma
zero_to_ten

<ipython-input-18-4ec072aa6a03>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)  # Bu kullanım gelecekte hata verebilir!


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Bazen başka bir tensörle aynı şekle sahip bir tensör oluşturmak isteyebilirsiniz.

Örneğin, önceki bir tensörle aynı şekle sahip, sadece sıfırlardan oluşan bir tensör.

Bunu yapmak için [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) veya [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) fonksiyonlarını kullanabilirsiniz. Bu fonksiyonlar sırasıyla `input` tensörünün aynı şekline sahip, sıfırlarla veya birlerle dolu bir tensör döndürür.


In [19]:
# Mevcut bir tensörle aynı boyutta sıfırlardan oluşan bir tensör oluşturma
ten_zeros = torch.zeros_like(input=zero_to_ten)  # zero_to_ten ile aynı boyutta

# Oluşturulan tensörü yazdırma
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensör Veri Türleri

PyTorch'ta kullanılabilir birçok farklı [tensör veri türü](https://pytorch.org/docs/stable/tensors.html#data-types) vardır.

Bazıları CPU için özel olup, bazıları ise GPU için daha uygundur.

Hangi veri türünün kullanılacağını öğrenmek zaman alabilir.

Genellikle `torch.cuda` gördüğünüzde, tensörün GPU için kullanıldığını anlayabilirsiniz (çünkü Nvidia GPU'ları CUDA adı verilen bir hesaplama araç setini kullanır).

En yaygın tür (ve genellikle varsayılan) `torch.float32` veya `torch.float`'tır.

Bu, "32-bit kayan nokta" olarak adlandırılır.

Ancak, 16-bit kayan nokta (`torch.float16` veya `torch.half`) ve 64-bit kayan nokta (`torch.float64` veya `torch.double`) da vardır.

Ve işler daha da karışsın diye, ayrıca 8-bit, 16-bit, 32-bit ve 64-bit tam sayılar da vardır.

Dahası var!

> **Not:** Bir tam sayı düz bir yuvarlak sayıdır, örneğin `7` iken bir kayan nokta sayısı ondalıklı bir değere sahiptir, örneğin `7.0`.

Bunların hepsinin nedeni **hesaplama hassasiyeti** ile ilgilidir.

Hassasiyet, bir sayıyı tanımlamak için kullanılan detay miktarıdır.

Hassasiyet değeri ne kadar yüksekse (8, 16, 32), sayıyı ifade etmek için kullanılan veri miktarı ve detay da o kadar artar.

Bu, derin öğrenme ve sayısal hesaplama için önemlidir çünkü çok sayıda işlem yapıyorsunuz ve üzerinde hesaplama yapacağınız daha fazla detay olduğunda, kullanmanız gereken hesaplama gücü de artar.

Yani, düşük hassasiyetli veri türleri genellikle daha hızlı hesaplanabilir ancak doğruluk gibi değerlendirme ölçütlerinde performans kaybına yol açabilir (daha hızlı hesaplanabilir ama daha az doğru).

> **Kaynaklar:**  
  * Tüm mevcut tensör veri türlerinin bir listesini görmek için [PyTorch belgesine göz atın](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Hesaplamada hassasiyetin ne olduğunu öğrenmek için [Wikipedia sayfasını okuyun](https://en.wikipedia.org/wiki/Precision_(computer_science)).

Şimdi belirli veri türlerine sahip tensörler nasıl oluşturulacağını görelim. Bunu `dtype` parametresini kullanarak yapabiliriz.


In [20]:
#Belirli Veri Tipleriyle Tensör Oluşturma




# 32-bit float tensör (varsayılan)
float32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

# 16-bit float tensör
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# 64-bit float tensör
float64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

# 32-bit integer tensör
int32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

# Tensörleri yazdırma
print("32-bit Float Tensor:", float32_tensor)
print("16-bit Float Tensor:", float16_tensor)
print("64-bit Float Tensor:", float64_tensor)
print("32-bit Integer Tensor:", int32_tensor)

32-bit Float Tensor: tensor([1., 2., 3.])
16-bit Float Tensor: tensor([1., 2., 3.], dtype=torch.float16)
64-bit Float Tensor: tensor([1., 2., 3.], dtype=torch.float64)
32-bit Integer Tensor: tensor([1, 2, 3], dtype=torch.int32)


Şekil sorunlarının (tensör şekilleri uyumsuz olduğunda) dışında, PyTorch'ta karşılaşacağınız diğer yaygın iki sorun veri türü ve cihaz sorunlarıdır.

Örneğin, bir tensör `torch.float32` iken, diğeri `torch.float16` olabilir (PyTorch, genellikle tensörlerin aynı formatta olmasını tercih eder).

Ya da bir tensörünüz CPU'da, diğer tensörünüz ise GPU'da olabilir (PyTorch, tensörler arasındaki hesaplamaların aynı cihazda yapılmasını tercih eder).

Cihaz konuşmasını daha sonra daha ayrıntılı olarak göreceğiz.

Şimdi, `dtype=torch.float16` olan bir tensör oluşturalım.


In [21]:
import torch

# Varsayılan olarak float32 tipinde bir tensör oluşturma
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,         # Belirtilmezse varsayılan olarak torch.float32 olur
                               device=None,        # Belirtilmezse CPU kullanılır
                               requires_grad=False)  # False olduğu için gradyan hesaplanmaz

# Tensörün şekli, veri tipi ve cihaz bilgisi
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

## Tensörlerden Bilgi Alma

Bir kez tensörler oluşturduğunuzda (ya da başkası veya bir PyTorch modülü sizin için oluşturduğunda), onlardan bazı bilgiler almak isteyebilirsiniz.

Bunları daha önce gördük ama tensörler hakkında öğrenmek isteyeceğiniz üç yaygın özellik şunlardır:
* `shape` - Tensörün şekli nedir? (bazı işlemler belirli şekil kurallarına ihtiyaç duyar)
* `dtype` - Tensör içinde yer alan elemanların veri türü nedir?
* `device` - Tensör hangi cihazda depolanıyor? (genellikle GPU veya CPU)

Şimdi rastgele bir tensör oluşturalım ve bununla ilgili detayları öğrenelim.


In [22]:
# 16-bit kayan noktalı (float16) tensör oluşturma
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)  # torch.half da kullanılabilir

# Tensörün veri tipini kontrol etme
float_16_tensor.dtype

torch.float16

## ℹ️ Tensörlerden Bilgi Alma

Tensörler oluşturduktan sonra (ister kendiniz, ister bir PyTorch modülü tarafından oluşturulmuş olsun), onlarla ilgili bazı bilgilere ihtiyaç duyabilirsiniz.

Daha önce de gördüğümüz gibi, tensörlerle ilgili en yaygın kullanılan üç özellik şunlardır:

- **`shape`** → Tensörün şekli nedir?  
  (*Bazı işlemler belirli şekil kurallarını gerektirir.*)  
- **`dtype`** → Tensördeki elemanlar hangi veri türünde saklanıyor?  
- **`device`** → Tensör hangi cihazda saklanıyor? (**CPU** veya **GPU**)

---

In [23]:
# 🔢 3x4 boyutunda rastgele bir tensör oluşturma
some_tensor = torch.rand(3, 4)

# ℹ️ Tensörün detaylarını yazdırma
print("Tensör:\n", some_tensor)
print(f"Tensörün Şekli (Shape): {some_tensor.shape}")
print(f"Tensörün Veri Tipi (Datatype): {some_tensor.dtype}")
print(f"Tensörün Cihazı (Device): {some_tensor.device}")  # Varsayılan olarak CPU'da tutulur


Tensör:
 tensor([[0.8086, 0.3897, 0.0087, 0.4006],
        [0.3816, 0.2700, 0.0922, 0.0510],
        [0.5456, 0.2015, 0.1747, 0.8109]])
Tensörün Şekli (Shape): torch.Size([3, 4])
Tensörün Veri Tipi (Datatype): torch.float32
Tensörün Cihazı (Device): cpu


> **Not:** PyTorch'ta sorunlarla karşılaştığınızda, genellikle yukarıdaki üç özellikten biriyle ilgili bir problemle karşılaşırsınız. Bu yüzden hata mesajları göründüğünde, kendinize küçük bir şarkı söyleyin: "what, what, where":
  * "*Tensörlerimin şekli ne? Veri türü ne ve nerede depolanıyor? Hangi şekil, hangi veri türü, nerede nerede nerede*"


## Tensörleri Manipüle Etme (Tensör Operations)

Derin öğrenmede, veriler (görüntüler, metinler, videolar, sesler, protein yapıları vb.) tensörler olarak temsil edilir.

Bir model, bu tensörleri inceleyerek ve tensörler üzerinde bir dizi işlem yaparak (1.000.000'larca işlem olabilir) giriş verilerindeki desenlerin bir temsilini oluşturur.

Bu işlemler genellikle şu temel işlemler arasında harika bir dans gibidir:
* Toplama
* Çıkarma
* Çarpma (eleman bazında)
* Bölme
* Matris çarpımı

Ve hepsi bu kadar. Tabii ki burada ve orada birkaç ekstra işlem olabilir ama bunlar sinir ağlarının temel yapı taşlarıdır.

Bu yapı taşlarını doğru şekilde üst üste koyarak, en sofistike sinir ağlarını oluşturabilirsiniz (tıpkı lego gibi!).


### Temel İşlemler

Başlangıç olarak, birkaç temel işlemle başlayalım: toplama (`+`), çıkarma (`-`), çarpma (`*`).

Bu işlemler, düşündüğünüz gibi çalışır.


In [24]:
# 🔢 Tensör oluşturma
tensor = torch.tensor([1, 2, 3])

# ➕ Tensöre 10 ekleme (eleman bazlı)
tensor + 10

tensor([11, 12, 13])

In [25]:
# ✖️ Tensörü 10 ile çarpma (eleman bazlı)
tensor * 10

tensor([10, 20, 30])

Yukarıdaki tensör değerlerinin `tensor([110, 120, 130])` şeklinde olmadığını fark ettiniz mi? Bunun nedeni, tensördeki değerlerin yalnızca yeniden atanmadıkça değişmemesidir.


In [26]:
# Tensörler yeniden atanmadıkça değişmez
tensor

tensor([1, 2, 3])

Şimdi bir sayıyı çıkaralım ve bu sefer `tensor` değişkenini yeniden atayalım.


In [27]:
# Çıkarma işlemi ve yeniden atama
tensor = tensor - 10

# Güncellenmiş tensörü yazdırma
print(tensor)

tensor([-9, -8, -7])


In [28]:
#Toplama işlemi ve yeniden atama
tensor = tensor + 10

# Güncellenmiş tensörü yazdırma
print(tensor)

tensor([1, 2, 3])


PyTorch ayrıca temel işlemleri gerçekleştirmek için [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (çarpma kısaltması) ve [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) gibi birçok yerleşik fonksiyona sahiptir.


In [29]:
# PyTorch fonksiyonlarını da kullanabilirsiniz
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [30]:
# Orijinal tensör hâlâ değişmedi
tensor

tensor([1, 2, 3])

Ancak, daha yaygın olarak `torch.mul()` yerine `*` gibi operator sembollerini kullanmak tercih edilir.


In [31]:
# 🔢 Eleman Bazlı Çarpma (Her eleman aynı indeksdeki elemanla çarpılır: 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Sonuç:", tensor * tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
Sonuç: tensor([1, 4, 9])


### Matris Çarpımı (İhtiyacınız Olan Her Şey)

Makine öğrenimi ve derin öğrenme algoritmalarında (sinir ağları gibi) en yaygın işlemlerden biri [matris çarpımı](https://www.mathsisfun.com/algebra/matrix-multiplying.html)'dır.

PyTorch, matris çarpımı işlevselliğini [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) metodunda sağlar.

Matris çarpımıyla ilgili hatırlamanız gereken iki ana kural şunlardır:

1. **İç boyutlar** uyumlu olmalıdır:
  * `(3, 2) @ (3, 2)` çalışmaz
  * `(2, 3) @ (3, 2)` çalışır
  * `(3, 2) @ (2, 3)` çalışır
2. Sonuç matrisi **dış boyutlar**a sahip olur:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Not:** Python'da "`@`" sembolü matris çarpımını temsil eder.

> **Kaynak:** `torch.matmul()` ile matris çarpımının tüm kurallarını [PyTorch belgesinde](https://pytorch.org/docs/stable/generated/torch.matmul.html) görebilirsiniz.

Şimdi bir tensör oluşturalım ve üzerinde eleman bazında çarpma ve matris çarpımı işlemleri yapalım.


In [32]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Eleman bazında çarpma ile matris çarpımı arasındaki fark, değerlerin eklenmesidir.

`tensor` değişkenimiz için `[1, 2, 3]` değerleriyle:

| İşlem | Hesaplama | Kod |
| ----- | ----- | ----- |
| **Eleman bazında çarpma** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matris çarpımı** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |


In [33]:
# ➗ Eleman Bazlı Çarpma (Element-wise Multiplication)
tensor * tensor

tensor([1, 4, 9])

In [34]:
#matris çarpımı (matrix multiplication)
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
# Matris çarpımı için "@" sembolü de kullanılabilir, ancak önerilmez.
tensor @ tensor


tensor(14)

Matris çarpımını elle yapabilirsiniz, ancak bu önerilmez.

Yerleşik `torch.matmul()` metodu daha hızlıdır.


In [36]:
%%time
# 🟰 Elle Matris Çarpımı (Manuel Hesaplama)
# ❗ For döngüleriyle işlem yapmaktan kaçının, çünkü hesaplama maliyeti yüksektir!

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

# Sonucu yazdırma
value

CPU times: user 2.99 ms, sys: 9 µs, total: 3 ms
Wall time: 6.92 ms


tensor(14)

In [37]:
%%time
# 🟰 Matris Çarpımı - PyTorch Yerleşik Fonksiyonu ile
torch.matmul(tensor, tensor)

CPU times: user 70 µs, sys: 20 µs, total: 90 µs
Wall time: 94.2 µs


tensor(14)

## Derin Öğrenmedeki En Yaygın Hatalardan Biri (Şekil Hataları)

Çünkü derin öğrenmenin çoğu, matrisler üzerinde çarpma ve işlemler yapmaktan ibarettir ve matrislerin, hangi şekil ve boyutların birleştirilebileceği konusunda sıkı kuralları vardır, derin öğrenmede karşılaşabileceğiniz en yaygın hatalardan biri şekil uyumsuzluklarıdır.


In [38]:
# 🔢 İki tensör oluşturuluyor
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# 🟰 Matris çarpımı (Bu işlem hata verecek!)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

`tensor_A` ve `tensor_B` arasındaki matris çarpımını iç boyutlarını eşleştirerek çalıştırabiliriz.

Bunu yapmanın yollarından biri, **transpoz** işlemidir (verilen bir tensörün boyutlarını değiştirmek).

PyTorch'ta transpoz işlemini şu şekilde gerçekleştirebilirsiniz:
* `torch.transpose(input, dim0, dim1)` - burada `input` transpoze edilecek tensördür ve `dim0` ve `dim1` değiştirilmesi gereken boyutlardır.
* `tensor.T` - burada `tensor` transpoze edilecek tensördür.

Şimdi ikincisini deneyelim.


In [39]:
# tensor_A ve tensor_B'yi görüntüle
print(tensor_A)
print(tensor_B)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [40]:
# tensor_A ve tensor_B.T'yi görüntüle
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [41]:
# tensor_B transpozu alındığında işlem çalışır
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")

# Matris çarpımını yap
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Ayrıca `torch.mm()` fonksiyonunu da kullanabilirsiniz, bu fonksiyon `torch.matmul()`'ın kısaltmasıdır.


In [42]:
# torch.mm, matmul için bir kısaltmadır
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Transpoz işlemi yapılmadan, matris çarpımı kuralları yerine getirilmediği için yukarıdaki gibi bir hata alırız.

Peki ya bir görsel?

![Matris çarpımının görsel demosu](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

Kendi matris çarpımı görsellerinizi şu adreste oluşturabilirsiniz: [http://matrixmultiplication.xyz/](http://matrixmultiplication.xyz/).

> **Not:** Bu tür bir matris çarpımı, iki matrisin [**nokta çarpımı**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) olarak da adlandırılır.


Sinir ağları, matris çarpımları ve nokta çarpımları ile doludur.

[`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) modülü (bunu daha sonra pratikte göreceğiz), aynı zamanda bir ileri besleme katmanı veya tam bağlı katman olarak bilinir, bir giriş `x` ile bir ağırlık matrisi `A` arasında matris çarpımı uygular.

$$
y = x\cdot{A^T} + b
$$

Burada:
* `x` katmanın girişi (derin öğrenme, `torch.nn.Linear()` gibi katmanların birbirinin üzerine yığıldığı bir yapıdır).
* `A` katman tarafından oluşturulan ağırlık matrisidir, başlangıçta rastgele sayılarla başlar ve bir sinir ağı, verilerdeki desenleri daha iyi temsil edecek şekilde bunları ayarladıkça değiştirilir (buradaki "`T`", çünkü ağırlık matrisi transpoze edilir).
  * **Not:** Ağırlık matrisini göstermek için genellikle `W` veya `X` gibi başka harfler de kullanılır.
* `b` ağırlıkları ve girişleri biraz kaydırmak için kullanılan bias terimidir.
* `y` çıktıdır (girişin bir manipülasyonu, bununla verilerdeki desenleri keşfetmeye çalışılır).

Bu, bir doğrusal fonksiyondur (lisede veya başka bir yerde $y = mx+b$ gibi bir şey görmüş olabilirsiniz), ve bir doğru çizmeyi sağlar!

Şimdi doğrusal bir katman ile oynayalım.

Aşağıdaki `in_features` ve `out_features` değerlerini değiştirin ve ne olduğunu görün.

Şekillerle ilgili bir şey fark ettiniz mi?


In [43]:
# 🔢 Rasgele ağırlıklar matrisinin tekrarlanabilir olmasını sağlamak için manuel tohum belirleme
torch.manual_seed(42)

# 🟰 Doğrusal katmanı oluşturma
linear = torch.nn.Linear(in_features=2,  # in_features = girişin iç boyutuyla uyumlu
                         out_features=6)  # out_features = dış boyutunu tanımlar

# 🧑‍💻 Giriş tensörünü tanımlama
x = tensor_A

# 🔄 Çıkışı hesaplama
output = linear(x)

# Sonuçları yazdırma
print(f"Giriş şekli: {x.shape}\n")
print(f"Çıktı:\n{output}\n\nÇıktı şekli: {output.shape}")

Giriş şekli: torch.Size([3, 2])

Çıktı:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Çıktı şekli: torch.Size([3, 6])


> **Soru:** Yukarıda `in_features` değerini 2'den 3'e değiştirirseniz ne olur? Bir hata alır mısınız? Girişi (`x`) hataya uyacak şekilde nasıl değiştirebilirsiniz? İpucu: Yukarıda `tensor_B` ile ne yapmamız gerektiğini hatırlayın.


Eğer daha önce yapmadıysanız, matris çarpımı başlangıçta kafa karıştırıcı bir konu olabilir.

Ama birkaç kez üzerinde oynayıp, hatta bazı sinir ağlarını açıp inceledikten sonra, her yerde olduğunu fark edeceksiniz.

Unutmayın, matris çarpımı tek ihtiyacınız olan şey.

![Matris çarpımı tek ihtiyacınız olan şey](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*Sinir ağı katmanlarına girmeye başladığınızda ve kendi katmanlarınızı inşa ettiğinizde, matris çarpımlarını her yerde bulacaksınız. **Kaynak:** https://marksaroufim.substack.com/p/working-class-deep-learner*


### Min, max, mean, sum gibi işlemlerle toplama (aggregation)

Şimdi tensörleri nasıl manipüle edebileceğimizi gördük, şimdi de bunları **toplayarak** (daha fazla değerden daha az değere) nasıl işlem yapabileceğimizi görelim.

Önce bir tensör oluşturacağız ve ardından bu tensörün **max**, **min**, **mean** ve **sum** gibi değerlerini bulacağız.



In [44]:
# 🔢 Bir tensör oluşturma
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


Now let's perform some aggregation.

In [45]:
# Minimum değeri yazdırma
print(f"Minimum: {x.min()}")

# Maksimum değeri yazdırma
print(f"Maximum: {x.max()}")

# Ortalamayı yazdırma (Hata alır çünkü integer tensörde mean kullanılamaz)
# print(f"Mean: {x.mean()}") # Bu hata verir

# Ortalamayı doğru şekilde yazdırma (float32 veri tipi ile)
print(f"Mean: {x.type(torch.float32).mean()}") # float32 veri tipi ile çalışır

# Toplam değeri yazdırma
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **Not:**  
> Bazı yöntemlerin, örneğin **`torch.mean()`**, tensörlerin **`torch.float32`** (en yaygın) veya başka bir özel veri tipinde olmasını gerektirdiğini görebilirsiniz, aksi takdirde işlem başarısız olur.

Aşağıda yapmış olduğumuz işlemi **`torch`** yöntemleriyle de gerçekleştirebilirsiniz.


In [46]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### **Pozisyonel Min/Max**

Bir tensörde maksimum veya minimum değerin bulunduğu **indeksi** bulmak için sırasıyla **`torch.argmax()`** ve **`torch.argmin()`** fonksiyonlarını kullanabilirsiniz.

Bu, **en yüksek (veya en düşük) değerin** pozisyonunu bilmek istediğinizde faydalıdır, ancak **değerin kendisini** değil. (Bunu, [softmax aktivasyon fonksiyonunu](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html) kullandığımız ilerleyen bölümlerde göreceğiz).


In [47]:
# 🔢 Tensör oluşturma
tensor = torch.arange(10, 100, 10)
print(f"Tensör: {tensor}")

# Maksimum ve minimum değerlerin indekslerini döndürme
print(f"Max değerin bulunduğu indeks: {tensor.argmax()}")
print(f"Min değerin bulunduğu indeks: {tensor.argmin()}")


Tensör: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Max değerin bulunduğu indeks: 8
Min değerin bulunduğu indeks: 0


### Tensör Veri Türünü Değiştirme

Daha önce belirtildiği gibi, derin öğrenme işlemleriyle ilgili yaygın bir sorun, tensörlerin farklı veri türlerinde olmasıdır.

Bir tensör `torch.float64` türünde, diğer tensör ise `torch.float32` türünde olduğunda bazı hatalarla karşılaşabilirsiniz.

Ama bunun bir çözümü var.

Tensörlerin veri türlerini, [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) fonksiyonu ile değiştirebilirsiniz. Burada `dtype` parametresi, kullanmak istediğiniz veri türüdür.

İlk olarak bir tensör oluşturacağız ve veri türünü kontrol edeceğiz (varsayılan `torch.float32`'dir).


In [48]:
# 🔢 Tensör oluşturma ve veri tipini kontrol etme
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)


torch.float32


Şimdi, daha önce oluşturduğumuz gibi başka bir tensör oluşturacağız ama bu sefer veri türünü `torch.float16` olarak değiştireceğiz.


In [49]:
# 🔢 float16 veri tipiyle bir tensör oluşturma
tensor_float16 = tensor.type(torch.float16)
print(tensor_float16)


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)


Ve benzer şekilde, bir **`torch.int8`** tensörü oluşturmak için aynı işlemi yapabiliriz.


In [50]:
# 🔢 int8 veri tipiyle bir tensör oluşturma
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


> **Not:** Farklı veri türleri başlangıçta kafa karıştırıcı olabilir. Ama şöyle düşünün, sayının değeri ne kadar küçükse (örneğin 32, 16, 8), bilgisayar o değeri o kadar az hassasiyetle depolar. Ve daha az depolama ile bu genellikle daha hızlı hesaplamalar ve daha küçük bir modelle sonuçlanır. Mobil tabanlı sinir ağları genellikle 8-bit tam sayılarla çalışır, daha küçük ve daha hızlı çalıştırılırlar ancak float32 karşılıklarına göre daha az doğrudur. Bununla ilgili daha fazla bilgi için [hesaplama hassasiyeti](https://en.wikipedia.org/wiki/Precision_(computer_science)) hakkında okuyabilirsiniz.

> **Egzersiz:** Şu ana kadar bir dizi tensör metodunu inceledik, ancak [`torch.Tensor` belgesinde](https://pytorch.org/docs/stable/tensors.html) daha bir sürü metod bulunuyor. 10 dakika boyunca belgenin içinde gezinip ilgini çekenleri incelemeni tavsiye ederim. Onlara tıklayarak ve kodla kendin yazıp ne olduğunu görmek oldukça öğretici olacaktır.


### Yeniden Şekillendirme, Yığınlama, Sıkıştırma ve Unsıkıştırma

Çoğu zaman, tensörlerin içinde değerleri değiştirmeden yalnızca boyutlarını değiştirmek istersiniz.

Bunu yapmak için bazı popüler yöntemler şunlardır:

| Yöntem | Kısa açıklama |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | `input`'ı uyumluysa `shape`'a yeniden şekillendirir, `torch.Tensor.reshape()` da kullanılabilir. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Orijinal tensörün yeni bir `shape`'te görünümünü döndürür ancak orijinal tensörle aynı veriyi paylaşır. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Bir dizi `tensors`'ı yeni bir boyut (`dim`) boyunca birleştirir, tüm `tensors` aynı boyutta olmalıdır. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | `input`'ı sıkıştırarak değeri `1` olan tüm boyutları kaldırır. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | `input`'ı, `dim` boyutunda değeri `1` olan bir boyut ekleyerek döndürür. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Orijinal `input`'ın bir *görünümünü* döndürür, boyutları `dims`'e göre düzenlenmiştir. |

Peki neden bunları yapalım?

Çünkü derin öğrenme modelleri (sinir ağları) her yönüyle tensörleri manipüle etmekle ilgilidir. Ve matris çarpımı kuralları nedeniyle, eğer şekil uyumsuzlukları varsa, hatalarla karşılaşırsınız. Bu yöntemler, tensörlerinizin doğru elemanlarının, diğer tensörlerle doğru elemanlarla karışmasını sağlamanıza yardımcı olur.

Şimdi bunları deneyelim.

İlk olarak bir tensör oluşturalım.


In [51]:
# Tensör Oluşturma
import torch
x = torch.arange(1., 8.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Şimdi **`torch.reshape()`** ile ekstra bir boyut ekleyelim.


In [52]:
# Ekstra bir boyut ekleme
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Ayrıca görünümü **`torch.view()`** ile değiştirebiliriz.


In [53]:
# Görünümü değiştir (aynı veriyi korur ancak görünümü değiştirir)
# Daha fazla bilgi: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Ancak unutmayın, **`torch.view()`** ile bir tensörün görünümünü değiştirmek, aslında **aynı** tensörün yeni bir görünümünü oluşturur.

Yani görünümü değiştirmek, orijinal tensörü de değiştirir.


In [54]:
# z'yi değiştirmek x'i de değiştirir
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Eğer yeni tensörümüzü kendisinin üzerine beş kez yığmak istersek, bunu **`torch.stack()`** ile yapabiliriz.


In [55]:
# Tensörleri üst üste yığma
x_stacked = torch.stack([x, x, x, x], dim=0) # dim'i dim=1 olarak değiştirip ne olduğunu görün
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Ya bir tensörden tüm tek boyutları (single dimensions) kaldırmak istersek?

Bunu yapmak için **`torch.squeeze()`** kullanabilirsiniz (ben bunu, tensörü sadece 1'den büyük boyutlara sahip olacak şekilde **sıkıştırmak** olarak hatırlıyorum).


In [56]:
print(f"Önceki tensör: {x_reshaped}")
print(f"Önceki şekil: {x_reshaped.shape}")

# x_reshaped'ten ekstra boyutu kaldırma
x_squeezed = x_reshaped.squeeze()
print(f"\nYeni tensör: {x_squeezed}")
print(f"Yeni şekil: {x_squeezed.shape}")


Önceki tensör: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Önceki şekil: torch.Size([1, 7])

Yeni tensör: tensor([5., 2., 3., 4., 5., 6., 7.])
Yeni şekil: torch.Size([7])


Ve **`torch.squeeze()`**'in tersini yapmak için, belirli bir indekste **1** değeri eklemek için **`torch.unsqueeze()`** kullanabilirsiniz.


In [57]:
print(f"Önceki tensör: {x_squeezed}")
print(f"Önceki şekil: {x_squeezed.shape}")

## unsqueeze ile ekstra bir boyut ekleyin
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nYeni tensör: {x_unsqueezed}")
print(f"Yeni şekil: {x_unsqueezed.shape}")


Önceki tensör: tensor([5., 2., 3., 4., 5., 6., 7.])
Önceki şekil: torch.Size([7])

Yeni tensör: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Yeni şekil: torch.Size([1, 7])


Ayrıca **`torch.permute(input, dims)`** ile eksen değerlerinin sırasını yeniden düzenleyebilirsiniz; burada **`input`**, yeni **`dims`** ile bir *görünüm* haline gelir.


In [58]:
# Belirli bir şekle sahip tensör oluşturma
x_original = torch.rand(size=(224, 224, 3))

# Orijinal tensörü eksen sırasını yeniden düzenlemek için permute etme
x_permuted = x_original.permute(2, 0, 1) # eksenleri 0->1, 1->2, 2->0 şeklinde kaydırır

print(f"Önceki şekil: {x_original.shape}")
print(f"Yeni şekil: {x_permuted.shape}")


Önceki şekil: torch.Size([224, 224, 3])
Yeni şekil: torch.Size([3, 224, 224])


> **Not:**  
> Çünkü **`permute()`** bir *görünüm* döndürür (orijinal ile aynı veriyi paylaşır), permütelenmiş tensördeki değerler, orijinal tensörle aynı olacaktır ve eğer görünümdeki değerleri değiştirirseniz, bu orijinal tensörün değerlerini de değiştirir.


## İndeksleme (Tensörlerden veri seçme)

Bazen tensörlerden belirli verileri seçmek isteyebilirsiniz (örneğin, sadece ilk sütun veya ikinci satır gibi).

Bunu yapmak için indeksleme kullanabilirsiniz.

Eğer Python listelerinde veya NumPy dizilerinde indeksleme yaptıysanız, PyTorch'ta tensörlerle indeksleme yapmak oldukça benzer.


In [59]:
# Tensör oluşturma
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

İndeksleme işlemi dış boyuttan iç boyuta doğru yapılır (kare parantezlere göz atın).


In [60]:
# Hadi, parantez parantez indeksleyelim
print(f"İlk kare parantez:\n{x[0]}")
print(f"İkinci kare parantez: {x[0][0]}")
print(f"Üçüncü kare parantez: {x[0][0][0]}")


İlk kare parantez:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
İkinci kare parantez: tensor([1, 2, 3])
Üçüncü kare parantez: 1


Ayrıca **`:`** kullanarak "bu boyuttaki tüm değerleri" belirtebilir ve ardından bir virgül (**`,`**) kullanarak başka bir boyut ekleyebilirsiniz.


In [61]:
# 0. boyuttaki tüm değerleri ve 1. boyuttaki 0. indeksi almak
x[:, 0]


tensor([[1, 2, 3]])

In [62]:
# 0. ve 1. boyuttaki tüm değerleri, ancak yalnızca 2. boyuttaki 1. indeksi almak
x[:, :, 1]


tensor([[2, 5, 8]])

In [63]:
# 0. ve 1. boyutların 0. indeksini almak ve 2. boyuttaki tüm değerleri almak
x[0, 0, :] # x[0][0] ile aynı


tensor([1, 2, 3])

İndeksleme başta oldukça kafa karıştırıcı olabilir, özellikle daha büyük tensörlerle çalışırken (ben hâlâ doğru yapmak için birkaç kez indeksleme yapmam gerekiyor). Ama biraz pratik yaparak ve veri kaşiflerinin mottosunu takip ederek (***görselleştir, görselleştir, görselleştir***), zamanla alışmaya başlayacaksınız.


## PyTorch Tensörleri ve NumPy

NumPy, popüler bir Python sayısal hesaplama kütüphanesi olduğundan, PyTorch'un NumPy ile düzgün bir şekilde etkileşim kurma işlevselliği vardır.

NumPy ile PyTorch arasında (ve geriye) kullanmak isteyeceğiniz iki ana yöntem şunlardır:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy dizisi -> PyTorch tensörü.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensörü -> NumPy dizisi.

Şimdi bunları deneyelim.


In [64]:
# NumPy dizisini tensöre çevirme
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **Not:**  
> Varsayılan olarak, NumPy dizileri **`float64`** veri tipiyle oluşturulur ve PyTorch tensörüne dönüştürdüğünüzde aynı veri tipi korunur (yukarıdaki gibi).  
>  
> Ancak, birçok PyTorch hesaplaması varsayılan olarak **`float32`** kullanır.  
>  
> Yani, NumPy dizinizi (**`float64`**) -> PyTorch tensörü (**`float64`**) -> PyTorch tensörü (**`float32`**) olarak dönüştürmek istiyorsanız, **`tensor = torch.from_numpy(array).type(torch.float32)`** kullanabilirsiniz.  
>  
> Yukarıda **`tensor`**'u yeniden atadığımız için, tensörü değiştirdiğinizde dizi aynı kalır.


In [65]:
# Diziyi değiştir, tensörü aynı tut
array = array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Ve eğer PyTorch tensöründen NumPy dizisine geçmek isterseniz, **`tensor.numpy()`** fonksiyonunu çağırabilirsiniz.


In [66]:
# Tensörden NumPy dizisine
tensor = torch.ones(7) # float32 veri tipiyle bir tensör oluşturma
numpy_tensor = tensor.numpy() # dtype=float32 olacak, eğer değiştirilmezse
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Ve yukarıdaki kural aynen geçerlidir; eğer orijinal **`tensor`**'ı değiştirirseniz, yeni **`numpy_tensor`** aynı kalır.


In [67]:
# Tensörü değiştir, diziyi aynı tut
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Tekrarlanabilirlik (Rastgeleliği Rastgelelikten Çıkarmaya Çalışmak)

Sinir ağları ve makine öğrenimi hakkında daha fazla şey öğrendikçe, rastgeleliğin ne kadar önemli bir rol oynadığını keşfedeceksiniz.

Aslında bu, **sahte rastgelelik**. Çünkü sonuçta, tasarlandıkları gibi bir bilgisayar temelde **deterministiktir** (her adım tahmin edilebilir), bu yüzden yarattıkları rastgelelikler, simüle edilmiş rastgeleliklerdir (bununla ilgili de tartışmalar olsa da, ben bir bilgisayar bilimci olmadığım için bunu kendiniz keşfetmenize bırakıyorum).

Peki bu, sinir ağları ve derin öğrenme ile nasıl ilişkilidir?

Sinir ağlarının, verilerdeki kalıpları tanımlamak için rastgele sayılarla başladığını ve bu sayıları tensör işlemleri (ve henüz tartışmadığımız birkaç başka şey) kullanarak iyileştirmeye çalıştığını konuştuk. Bu sayılar başlangıçta kötü tanımlamalardır ve verilerdeki kalıpları daha iyi tanımlamak için bu rastgele sayılar iyileştirilmeye çalışılır.

Kısacası:

``rastgele sayılarla başla -> tensör işlemleri -> daha iyi hale getirmeye çalış (defalarca ve tekrar)``

Rastgelelik güzel ve güçlü olsa da, bazen biraz daha az rastgelelik istersiniz.

Neden?

Çünkü tekrarlanabilir deneyler yapabilmek istersiniz.

Örneğin, X performansını elde edebilen bir algoritma oluşturursunuz.

Ve sonra arkadaşınız bunu deneyerek sizin deli olmadığınızı doğrulamak ister.

Bunu nasıl yapabilirler?

İşte burada **tekrarlanabilirlik** devreye giriyor.

Başka bir deyişle, aynı kodu çalıştıran bilgisayarımda aldığım aynı (veya çok benzer) sonuçları, sizin bilgisayarınızda alabilir misiniz?

Hadi PyTorch'ta tekrarlanabilirliğe kısa bir örnek bakalım.

İki rastgele tensör oluşturacağız. Çünkü rastgele olduklarından, farklı olmalarını beklersiniz, değil mi?


In [68]:
import torch

# İki rastgele tensör oluşturma
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensör A:\n{random_tensor_A}\n")
print(f"Tensör B:\n{random_tensor_B}\n")
print(f"Tensör A, Tensör B'ye eşit mi? (herhangi bir yerde)")
random_tensor_A == random_tensor_B


Tensör A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensör B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Tensör A, Tensör B'ye eşit mi? (herhangi bir yerde)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Beklediğiniz gibi, tensörler farklı değerlerle çıktı.

Ama ya iki rastgele tensörün *aynı* değerlere sahip olmasını isteseydiniz?

Yani tensörler hala rastgele değerlere sahip olacak ama aynı "lezzette" olacaklardı.

İşte burada **`torch.manual_seed(seed)`** devreye giriyor; burada **`seed`** bir tam sayıdır (mesela **`42`** olabilir ama başka bir şey de olabilir) ve rastgeleliği **lezzetlendiren** bir değerdir.

Hadi bunu deneyelim ve daha fazla *lezzetlendirilmiş* rastgele tensörler oluşturalım.


In [69]:
import torch
import random

# Rastgele tohum değerini ayarla
RANDOM_SEED = 42 # Bunu farklı değerlere değiştirerek aşağıdaki sayılarda ne olduğunu görebilirsiniz
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Her yeni rand() çağrıldığında tohumun sıfırlanması gerekir
# Bunu yapmazsanız, tensor_D, tensor_C'ye farklı olurdu
torch.random.manual_seed(seed=RANDOM_SEED) # Bu satırı yorum satırına almayı deneyin ve ne olacağını görün
random_tensor_D = torch.rand(3, 4)

print(f"Tensör C:\n{random_tensor_C}\n")
print(f"Tensör D:\n{random_tensor_D}\n")
print(f"Tensör C, Tensör D'ye eşit mi? (herhangi bir yerde)")
random_tensor_C == random_tensor_D


Tensör C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensör D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensör C, Tensör D'ye eşit mi? (herhangi bir yerde)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Harika!

Görünüşe göre tohum ayarlamak işe yaramış.

> **Kaynak:** Şu ana kadar ele aldıklarımız, PyTorch'ta tekrarlanabilirlik konusunda yalnızca yüzeyi çiziyor. Genel olarak tekrarlanabilirlik ve rastgele tohumlar hakkında daha fazla bilgi için şunları incelemenizi öneririm:
> * [PyTorch tekrarlanabilirlik dokümantasyonu](https://pytorch.org/docs/stable/notes/randomness.html) (iyi bir alıştırma, bunu 10 dakika boyunca okuyup anlamasanız da, buna aşina olmak önemlidir).
> * [Wikipedia rastgele tohum sayfası](https://en.wikipedia.org/wiki/Random_seed) (bu, rastgele tohumlar ve genel olarak sahte rastgelelik hakkında iyi bir genel bakış sağlar).


## Tensörleri GPU'larda Çalıştırma (ve Daha Hızlı Hesaplamalar Yapma)

Derin öğrenme algoritmaları çok fazla sayısal işlem gerektirir.

Ve varsayılan olarak bu işlemler çoğunlukla bir CPU'da (işlemci) yapılır.

Ancak, bir GPU (grafik işleme birimi) adında başka bir yaygın donanım türü vardır, bu donanım genellikle sinir ağlarının ihtiyaç duyduğu belirli türdeki işlemleri (matris çarpımları) CPU'lardan çok daha hızlı bir şekilde gerçekleştirebilir.

Bilgisayarınızda bir tane olabilir.

Eğer öyleyse, sinir ağlarını eğitmek için her fırsatta kullanmaya çalışmalısınız çünkü büyük ihtimalle eğitim süresini dramatik şekilde hızlandıracaktır.

GPU'ya erişmenin ve PyTorch'u GPU kullanacak şekilde yapılandırmanın birkaç yolu vardır.

> **Not:** Bu kurs boyunca "GPU"dan bahsederken, [CUDA etkinleştirilmiş bir Nvidia GPU'yu](https://developer.nvidia.com/cuda-gpus) kast ediyorum (CUDA, GPU'ların yalnızca grafik değil, genel amaçlı hesaplama için de kullanılmasını sağlayan bir hesaplama platformu ve API'sidir) aksi belirtilmedikçe.


### 1. GPU'ya Erişim

GPU dediğimde ne olduğunu zaten biliyor olabilirsiniz. Ancak bilmiyorsanız, birine erişim sağlamak için birkaç yol vardır.

| **Yöntem** | **Kurulum Zorluğu** | **Avantajlar** | **Dezavantajlar** | **Nasıl Kurulur** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Kolay | Ücretsiz, neredeyse sıfır kurulum gerektirir, çalışmaları başkalarıyla bir bağlantı kadar kolay paylaşabilirsiniz | Verilerinizi kaydetmez, sınırlı hesaplama gücü, zaman aşımına uğrayabilir | [Google Colab Kılavuzunu Takip Edin](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Kendi bilgisayarınızı kullanma | Orta | Her şeyi yerel olarak kendi bilgisayarınızda çalıştırabilirsiniz | GPU'lar ücretsiz değil, önceden maliyet gerektirir | [PyTorch kurulum yönergelerini takip edin](https://pytorch.org/get-started/locally/) |
| Bulut bilişim (AWS, GCP, Azure) | Orta-Zor | Küçük ön maliyet, neredeyse sonsuz hesaplama erişimi | Sürekli çalıştırırsanız pahalı olabilir, doğru şekilde kurmak zaman alabilir | [PyTorch bulut kurulum kılavuzunu takip edin](https://pytorch.org/get-started/cloud-partners/) |

GPU'ları kullanmak için daha fazla seçenek vardır ancak yukarıdaki üç seçenek şimdilik yeterli olacaktır.

Kişisel olarak, küçük ölçekli deneyler (ve bu kursu oluşturma) için Google Colab ve kendi bilgisayarımın bir kombinasyonunu kullanıyorum ve daha fazla hesaplama gücüne ihtiyaç duyduğumda bulut kaynaklarına başvuruyorum.

> **Kaynak:** Kendi GPU'nuzu satın almayı düşünüyorsanız ancak ne alacağınızı bilmiyorsanız, [Tim Dettmers'ın harika bir kılavuzu var](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

Bir Nvidia GPU'nuzun olup olmadığını kontrol etmek için, `!nvidia-smi` komutunu çalıştırabilirsiniz, burada `!` (aynı zamanda bang olarak da bilinir) "bunu komut satırında çalıştır" anlamına gelir.


In [70]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


Eğer erişebileceğiniz bir Nvidia GPU'nuz yoksa, yukarıdaki çıktı şu şekilde görünecektir:



### 2. PyTorch'u GPU üzerinde çalıştırma

Bir GPU'ya erişim sağladıktan sonra, bir sonraki adım, PyTorch'u verileri (tensörleri) depolamak ve veriler üzerinde hesaplamalar yapmak (tensörler üzerinde işlemler gerçekleştirmek) için kullanmaktır.

Bunu yapmak için **`torch.cuda`** paketini kullanabilirsiniz.

Bundan bahsetmek yerine, bunu deneyelim.

PyTorch'un bir GPU'ya erişimi olup olmadığını, **[`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available)** fonksiyonunu kullanarak test edebilirsiniz.


In [71]:
# GPU'yu kontrol etme
import torch
torch.cuda.is_available()


False

Eğer yukarıdaki çıktı **`True`** ise, PyTorch GPU'yu görebilir ve kullanabilir, eğer **`False`** çıkarsa, GPU'yu göremez ve bu durumda kurulum adımlarını tekrar gözden geçirmeniz gerekecek.

Şimdi, kodunuzu CPU *veya* mevcutsa GPU üzerinde çalışacak şekilde ayarlamak istediğinizi varsayalım.

Bu şekilde, siz veya birisi kodunuzu çalıştırmaya karar verdiğinde, kullandıkları hesaplama cihazına bakılmaksızın çalışacaktır.

Bir `device` değişkeni oluşturalım ve hangi tür cihazın mevcut olduğunu saklayalım.


In [72]:
# Cihaz türünü ayarlama
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

Yukarıdaki çıktı **`"cuda"`** ise, tüm PyTorch kodumuzu mevcut CUDA cihazını (GPU) kullanacak şekilde ayarlayabileceğimiz anlamına gelir ve eğer **`"cpu"`** çıkarsa, PyTorch kodumuz CPU üzerinde çalışacaktır.

> **Not:** PyTorch'ta, [**cihazdan bağımsız kod**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code) yazmak en iyi uygulamadır. Bu, CPU'da (her zaman mevcut) veya GPU'da (mevcutsa) çalışacak kod anlamına gelir.

Daha hızlı hesaplamalar yapmak istiyorsanız, bir GPU kullanabilirsiniz, ancak *çok* daha hızlı hesaplamalar yapmak istiyorsanız, birden fazla GPU kullanabilirsiniz.

PyTorch'un erişebileceği GPU sayısını, **[`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count)** fonksiyonunu kullanarak öğrenebilirsiniz.


In [73]:
# Cihaz sayısını sayma
torch.cuda.device_count()


0

PyTorch'un erişebileceği GPU sayısını bilmek, bir işlemi bir GPU'da ve başka bir işlemi diğer GPU'da çalıştırmak isterseniz faydalıdır (PyTorch ayrıca bir işlemi *tüm* GPU'lar üzerinde çalıştırmanıza olanak tanıyan özelliklere sahiptir).


### 2.1 PyTorch'u Apple Silicon'da Çalıştırma

Apple'ın M1/M2/M3 GPU'larında PyTorch çalıştırmak için **[`torch.backends.mps`](https://pytorch.org/docs/stable/notes/mps.html)** modülünü kullanabilirsiniz.

macOS ve PyTorch sürümlerinin güncel olduğundan emin olun.

PyTorch'un bir GPU'ya erişimi olup olmadığını **`torch.backends.mps.is_available()`** ile test edebilirsiniz.


In [74]:
# Apple Silicon GPU'yu kontrol etme
import torch
torch.backends.mps.is_available() # Not: Bu, bir Mac'te çalışmıyorsanız false döndürecektir


False

In [75]:
# Cihaz türünü ayarlama
device = "mps" if torch.backends.mps.is_available() else "cpu"
device


'cpu'

Yukarıdaki çıktı **`"mps"`** ise, tüm PyTorch kodumuzu mevcut Apple Silicon GPU'sunu kullanacak şekilde ayarlayabileceğimiz anlamına gelir.


In [76]:
if torch.cuda.is_available():
    device = "cuda"  # NVIDIA GPU'yu kullan (eğer mevcutsa)
elif torch.backends.mps.is_available():
    device = "mps"  # Apple Silicon GPU'yu kullan (eğer mevcutsa)
else:
    device = "cpu"  # GPU yoksa varsayılan olarak CPU kullan


### 3. Tensörleri (ve modelleri) GPU'ya koyma

Tensörleri (ve modelleri, bunu daha sonra göreceğiz) belirli bir cihaza koymak için onlara **`to(device)`** fonksiyonunu çağırabilirsiniz. Burada **`device`**, tensörün (veya modelin) gitmesini istediğiniz hedef cihazdır.

Bunu neden yapmalısınız?

GPU'lar, CPU'lardan çok daha hızlı sayısal hesaplamalar yapar ve eğer bir GPU mevcut değilse, **cihazdan bağımsız kodumuz** (yukarıya bakın) sayesinde kod CPU üzerinde çalışacaktır.

> **Not:** **`to(device)`** kullanarak bir tensörü GPU'ya koymak (örneğin **`some_tensor.to(device)`**) o tensörün bir kopyasını döndürür; örneğin, aynı tensör hem CPU'da hem de GPU'da olacaktır. Tensörleri üzerine yazmak için onları yeniden atayın:
>
> `some_tensor = some_tensor.to(device)`

Hadi, bir tensör oluşturalım ve onu GPU'ya koyalım (eğer mevcutsa).


In [77]:
# Tensör oluşturma (varsayılan olarak CPU üzerinde)
tensor = torch.tensor([1, 2, 3])

# Tensör GPU'da değil
print(tensor, tensor.device)

# Tensörü GPU'ya taşıma (eğer mevcutsa)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

Eğer bir GPU'nuz mevcutsa, yukarıdaki kod şu şekilde bir çıktı verecektir:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

İkinci tensörün **`device='cuda:0'`** olduğunu fark edin, bu, tensörün mevcut 0. GPU'da depolandığını gösterir (GPU'lar 0'dan başlar, eğer iki GPU mevcutsa, sırasıyla `'cuda:0'` ve `'cuda:1'` olur, bu şekilde `'cuda:n'`'e kadar devam eder).


### 4. Tensörleri CPU'ya geri taşıma

Ya tensörü geri CPU'ya taşımak istersek?

Örneğin, tensörlerinizle NumPy ile etkileşimde bulunmak isterseniz bunu yapmak isteyebilirsiniz (NumPy, GPU'yu kullanmaz).

Hadi, **`torch.Tensor.numpy()`** metodunu **`tensor_on_gpu`** üzerinde deneyelim.


In [78]:
# Eğer tensör GPU'daysa, NumPy'ye dönüştürülemez (bu hata verecektir)
tensor_on_gpu.numpy()


array([1, 2, 3])

Bunun yerine, bir tensörü CPU'ya geri almak ve NumPy ile kullanılabilir hale getirmek için **[`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html)** kullanabiliriz.

Bu, tensörü CPU belleğine kopyalar, böylece CPU'lar ile kullanılabilir hale gelir.


In [79]:
# Bunun yerine, tensörü geri CPU'ya kopyala
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

Yukarıdaki işlem, GPU tensörünün bir kopyasını CPU belleğine döndürür, böylece orijinal tensör hala GPU üzerinde kalır.


In [80]:
tensor_on_gpu

tensor([1, 2, 3])