<a href="https://colab.research.google.com/github/esradag/pytorch-derin-ogrenme/blob/main/PytorchTemelleri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Nedir?
PyTorch, açık kaynaklı bir makine öğrenimi ve derin öğrenme framework’üdür.

#PyTorch Ne İçin Kullanılır?
PyTorch, Python kodu kullanarak veri işleme ve makine öğrenimi algoritmaları yazmayı sağlar.

#PyTorch Temel Konuları

##Tensörlere Giriş:
Tensörler, makine öğrenimi ve derin öğrenme modellerinin temel yapı taşlarıdır. Tüm veri işlemleri ve hesaplamalar tensörler üzerinden gerçekleştirilir.

##Tensör Oluşturma:
Tensörler; görüntüler, metinler ve sayı tabloları gibi farklı veri türlerini temsil edebilir. PyTorch, farklı boyut ve türde tensörler oluşturmayı kolaylaştırır.

##Tensörlerden Bilgi Alma:
Tensörlerde depolanan verilere erişmek ve bu bilgileri analiz etmek için çeşitli yöntemler sunar.

##Tensörleri Manipüle Etme:
Tensörler üzerinde toplama, çarpma ve birleştirme gibi matematiksel ve yapısal işlemler kolaylıkla yapılabilir.

##Tensör Şekilleriyle Çalışma:
Makine öğreniminde sıkça karşılaşılan yanlış şekilli tensörlerin yönetimi için şekil dönüştürme ve uyumlu hale getirme işlemleri uygulanır.

##Tensörlerde İndeksleme:
Python listeleri veya NumPy dizileriyle benzer şekilde, tensörlerde de çok boyutlu indeksleme yapılabilir. Bu sayede veriye kolay erişim sağlanır.

##PyTorch ve NumPy Karışımı:
PyTorch tensörleri (torch.Tensor) ve NumPy dizileri (np.ndarray) arasında veri dönüşümleri kolaylıkla yapılabilir. Böylece her iki kütüphanenin avantajlarından yararlanılır.

##Yeniden Üretilebilirlik:
Makine öğreniminde deneylerin tutarlılığı için rastgeleliğin kontrol edilmesi önemlidir. PyTorch, belirli bir rastgelelik seviyesini sabitleyerek sonuçların tekrarlanabilir olmasını sağlar.

##Tensörleri GPU’da Çalıştırma:
PyTorch, GPU (Grafik İşleme Birimi) desteğiyle büyük veri ve karmaşık hesaplamaları hızlı bir şekilde gerçekleştirir. Bu sayede model eğitimi ve tahmin süreçleri hız kazanır.

#PyTorch'u İçe Aktarma
> **Not:** Bu kodu çalıştırmadan önce, [PyTorch kurulum adımlarını ] (https://pytorch.org/get-started/locally/)  tamamlamış olmanız gerekir.
> Ancak, **Google Colab kullanıyorsanız **herhangi bir ek kurulum yapmanıza gerek yoktur çünkü PyTorch ve diğer gerekli kütüphaneler Colab'de önceden yüklüdür.

PyTorch'u içe aktararak ve kullanılan sürümü kontrol ederek başlayalım:

In [1]:
import torch
torch.__version__

'2.5.1+cu121'

## Tensörlere Giriş

Tensörler, makine öğreniminin temel yapı taşıdır.  
Görevleri, verileri sayısal bir şekilde temsil etmektir.

Örneğin, bir resmi **`[3, 224, 224]`** şeklinde bir tensör olarak temsil edebiliriz. Bu şu anlama gelir:

- **3** renk kanalı (**kırmızı**, **yeşil**, **mavi**)  
- **224** piksel **yükseklik**  
- **224** piksel **genişlik**  

Tensör dilinde bu, **üç boyutlu** bir tensördür:  

1. **Renk kanalları** (`colour_channels`)  
2. **Yükseklik** (`height`)  
3. **Genişlik** (`width`)  


### Tensör Oluşturma

PyTorch, tensörler üzerine kurulmuş güçlü bir kütüphanedir. Hatta [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) sınıfına özel bir dokümantasyon sayfası da bulunmaktadır.


İlk oluşturulacak veri türü bir **skaler**dir.

**Skaler** nedir?  
- Tek bir sayıdan oluşan en basit veri türüdür.  
- Tensör terminolojisinde **sıfır boyutlu (0D)** bir tensör olarak adlandırılır.  


In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

### Tensörlerin Boyutlarını Kontrol Etme

Yukarıda ekrana **`tensor(7)`** çıktısını gördünüz mü?  

Bu, **scalar** tek bir sayı olmasına rağmen, PyTorch'ta **`torch.Tensor`** türünde olduğunu gösterir.

Bir tensörün boyutunu kontrol etmek için **`.ndim`** özelliğini kullanabiliriz.


In [3]:
scalar.ndim

0

### Vektör (Vector) Nedir?

Şimdi de **vektör** kavramını inceleyelim.  

Bir **vektör**, tek boyutlu (**1D**) bir tensördür ancak birden fazla sayı içerebilir.

Örneğin, evinizdeki oda bilgilerini temsil etmek için bir vektör kullanabilirsiniz:  
- `[3, 2]` → **3** yatak odası ve **2** banyo  
- `[3, 2, 2]` → **3** yatak odası, **2** banyo ve **2** otopark alanı  

Burada dikkat edilmesi gereken önemli nokta, bir **vektörün** (ve tensörlerin) neyi temsil edeceği konusunda esnek olmasıdır.



In [4]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

### Vektörün Boyutunu ve Şeklini Anlama

İlginç değil mi? **`vector`** iki sayı içeriyor ancak yalnızca **tek bir boyuta** sahip.  

Bu durumu daha iyi anlamanız için size küçük bir ipucu vereyim:  

**Bir tensörün kaç boyutlu olduğunu, köşeli parantez sayısından anlayabilirsiniz (`[`).**  
Ve yalnızca **bir tarafı** saymanız yeterlidir.

Örneğin:  
- **`[1, 2, 3]`** → **1 boyutlu** tensör (**vektör**)  
- **`[[1, 2, 3], [4, 5, 6]]`** → **2 boyutlu** tensör (**matris**)  
- **`[[[1], [2]], [[3], [4]]]`** → **3 boyutlu** tensör  

Peki, **`vector`** kaç köşeli parantez içeriyor?  

---

Tensörlerle ilgili önemli bir diğer kavram ise **`shape`** (şekil) özelliğidir.  
**`shape`**, tensör içindeki elemanların nasıl düzenlendiğini gösterir.


In [5]:
# Vektörün şeklini kontrol etme
vector.shape

torch.Size([2])

### Matris (Matrix) Nedir?

Bir önceki işlemde elde ettiğimiz sonuç **`torch.Size([2])`** oldu. Bu, vektörümüzün **[2]** şeklinde olduğunu gösterir.  
Bunun nedeni, köşeli parantezler içine **iki eleman** yerleştirmiş olmamızdır (`[7, 7]`).

Şimdi bir **matris** oluşturalım.

**Matris**, **iki boyutlu (2D)** bir tensördür.  
Örneğin, aşağıdaki gibi bir yapı matristir:



In [6]:

# Matris (2D tensör) oluşturma
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

## Matrisler (Matrix) – Çok Boyutlu Veri Temsili

**Vektörler** tek boyutlu tensörlerken, **matrisler** ekstra bir boyut ekleyerek verileri daha esnek ve karmaşık bir şekilde temsil eder.  
Matrisler, **satır (row)** ve **sütun (column)** yapısından oluşur ve genellikle **2 boyutlu (2D)** tensörler olarak adlandırılır.



### 📏 Matrisin Boyut Sayısını Kontrol Etme

Bir tensörün kaç boyutlu olduğunu öğrenmek için **`.ndim`** özelliğini kullanabiliriz.  
Bu özellik, tensörün boyut (dimension) sayısını döndürür.

In [7]:
# Matrisin boyut sayısını kontrol etme
MATRIX.ndim

2


### 📐 Matrisin Şekli (Shape) Ne Olacak?

**`MATRIX`** tensörünün **2 boyutlu (2D)** olduğunu öğrendik.  
(Bunu, dıştaki köşeli parantezleri sayarak da anlayabiliriz! 😉)

Peki, bu matrisin **şekli (shape)** nasıl olacak?

In [8]:
# Matrisin şeklini kontrol etme
MATRIX.shape

torch.Size([2, 2])

### 🔢 Tensör (Tensor) Oluşturma

Şimdi daha genel ve çok boyutlu bir **tensör** oluşturalım.  
**Tensörler**, skaler, vektör ve matrislerden daha fazla boyut içerebilir ve çok daha karmaşık verileri temsil etmek için kullanılır.

Örneğin, **3 boyutlu (3D)** bir tensör oluşturalım.

In [9]:
# 3 boyutlu bir tensör oluşturma
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

# Tensörü yazdırma
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


### 🔎 Tensörler Neredeyse Her Şeyi Temsil Edebilir!

Gerçekten etkileyici bir tensör oluşturduk! 🎉

**Tensörler**, hemen hemen her türlü veriyi temsil edebilir.  
Az önce oluşturduğumuz tensör, örneğin bir **steak ve badem ezmesi** dükkanının satış verilerini gösterebilir! 🍖🥜

📊 **Görsel Temsil:**  
![Steak ve Badem Ezmesi Satışları](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)  

Bu tensör, haftanın günlerine göre **steak** ve **badem ezmesi** satışlarını temsil ediyor olabilir.


### ❓ **Kaç Boyutlu Bir Tensör?**

Şimdi bu tensörün kaç boyutlu olduğunu bulalım!  
📌 **İpucu:** Dıştaki köşeli parantezleri (`[ ]`) sayın!

In [10]:
# TENSOR değişkeninin boyut sayısını kontrol etme
TENSOR.ndim

3

In [11]:
# TENSOR değişkeninin şeklini (boyutlarının düzenini) kontrol etme
TENSOR.shape

torch.Size([1, 3, 3])

### 🔎 Tensör Boyutları ve İsimlendirme

**`torch.Size([1, 3, 3])`** çıktısı bize şunu söylüyor:  
- Dıştan içe doğru gidildiğinde, **1 adet 3x3 matris** olduğunu anlıyoruz.  
- Yani bu tensör, **3 boyutlu (3D)** bir yapıya sahip.

📊 **Görsel Temsil:**  
![Farklı Tensör Boyutları](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

---

### ✏️ **İsimlendirme Kuralları**

Dikkat ettiyseniz, küçük harfleri **`scalar`** ve **`vector`** için, büyük harfleri ise **`MATRIX`** ve **`TENSOR`** için kullandım.  
Bu kasıtlı bir tercihti ve pratikte yaygın bir uygulamadır.  

📌 **Genel İsimlendirme:**  
- **Skaler (scalar)** ve **vektör (vector)** → Genellikle **küçük harf** kullanılır (**`a`, `y`**)  
- **Matris (matrix)** ve **tensör (tensor)** → Genellikle **büyük harf** kullanılır (**`X`, `W`**)  

⚠️ **Not:** PyTorch'ta genellikle tüm veriler **`torch.Tensor`** olarak tanımlanır. Ancak içeriğin boyutu ve şekli, verinin **skaler**, **vektör**, **matris** veya daha yüksek boyutlu bir tensör olup olmadığını belirler.

---

### 📊 **Özet Tablo**

| **İsim**   | **Nedir?**                                      | **Boyut Sayısı**  | **Genel İsimlendirme** |
|------------|--------------------------------------------------|-------------------|------------------------|
| **scalar** | Tek bir sayı                                     | **0**             | Küçük harf (`a`)      |
| **vector** | Yönü olan sayı dizisi (örneğin rüzgar hızı)      | **1**             | Küçük harf (`y`)      |
| **matrix** | 2 boyutlu sayı dizisi                           | **2**             | Büyük harf (`Q`)      |
| **tensor** | **n** boyutlu sayı dizisi                       | **0 ve üzeri**    | Büyük harf (`X`)      |

📌 **Ek Bilgi:**  
- **0D** → **Skaler**  
- **1D** → **Vektör**  
- **2D** → **Matris**  
- **3D ve üzeri** → **Tensör**  

---

### 🎨 **Görsel Temsil**

![Skaler, Vektör, Matris ve Tensör Görseli](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

Bu görselde farklı boyutlardaki tensörler arasındaki farkları açıkça görebilirsiniz.

> 💡 **Unutmayın:** PyTorch’ta tüm veriler tensör olarak işlenir. Ancak bu tensörlerin boyutu ve şekli, onları nasıl yorumladığımızı belirler!


### 🎲 Rastgele Tensörler (Random Tensors)

Daha önce tensörlerin verileri temsil ettiğini öğrendik.  
Makine öğrenimi modelleri (özellikle **sinir ağları**) bu tensörleri işleyerek içindeki kalıpları ve ilişkileri keşfeder.

Ancak, PyTorch ile makine öğrenimi modeli geliştirirken, tensörleri elle oluşturmak (şu ana kadar yaptığımız gibi) oldukça nadir bir durumdur.

---

### 🔄 **Makine Öğreniminde Rastgele Tensörlerin Önemi**

Makine öğrenimi modelleri genellikle başlangıçta rastgele sayılarla doldurulmuş büyük tensörlerle başlar.  
Model, bu rastgele sayıları veriyi işlerken günceller ve daha iyi tahminler yapmayı öğrenir.

Bu süreci şu şekilde özetleyebiliriz:

`Rastgele sayılarla başla → Veriye bak → Sayıları güncelle → Veriye tekrar bak → Sayıları güncelle...`

📌 **Veri bilimcisi** olarak, modelin:  
- **Başlangıç değerlerini (initialization)** nasıl belirleyeceğini,  
- **Veriyi (representation)** nasıl işleyeceğini ve  
- **Sayıları (optimization)** nasıl güncelleyeceğini kontrol edebilirsiniz.

Bu adımları ilerleyen bölümlerde uygulamalı olarak inceleyeceğiz.  
Şimdilik, rastgele sayı içeren tensörleri nasıl oluşturacağımıza bakalım.

---

### 📝 **Rastgele Tensör Oluşturma**

Rastgele sayı içeren tensörleri oluşturmak için [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) fonksiyonunu kullanabiliriz.  
Bu fonksiyon, **0 ile 1** arasında rastgele sayı üreten bir tensör oluşturur.



In [12]:
# (3, 4) boyutunda rastgele sayı içeren bir tensör oluşturma
random_tensor = torch.rand(size=(3, 4))

# Tensörü ve veri tipini yazdırma
random_tensor, random_tensor.dtype

(tensor([[0.4131, 0.4675, 0.0333, 0.9974],
         [0.1534, 0.5545, 0.2321, 0.3569],
         [0.6491, 0.9851, 0.5991, 0.1810]]),
 torch.float32)

### 🎨 Görsel Verilere Uygun Rastgele Tensör Oluşturma

**`torch.rand()`** fonksiyonunun en büyük avantajlarından biri, **`size`** parametresini istediğimiz gibi ayarlayabilmemizdir.  
Bu sayede, farklı veri türleri ve boyutlarına uygun tensörler oluşturabiliriz.

Örneğin, görseller genellikle şu boyutlarda temsil edilir:  
**`[224, 224, 3]`** → **[yükseklik, genişlik, renk kanalları]**  
- **224** piksel yükseklik  
- **224** piksel genişlik  
- **3** renk kanalı (**RGB**: Kırmızı, Yeşil, Mavi)

Bu tür bir tensör, görüntü işleme projelerinde yaygın olarak kullanılır.


In [13]:
# (224, 224, 3) boyutunda rastgele sayı içeren bir tensör oluşturma
random_image_size_tensor = torch.rand(size=(224, 224, 3))

# Tensörün şeklini (shape) ve boyut sayısını (ndim) kontrol etme
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### 🟢 **Sıfır ve Birlerle Dolu Tensörler (Zeros and Ones)**

Bazen tensörleri sadece **0** veya **1** değerleriyle doldurmak isteyebilirsiniz.  
Bu özellikle **maskelere** ihtiyaç duyulan durumlarda kullanılır.  

📌 **Maskeleme (Masking):**  
Belirli verileri modelden gizlemek veya dikkate almamasını sağlamak için tensörlerin bazı kısımlarını **0** ile doldururuz.  
Bu yöntem, modelin öğrenmesini kontrol etmek için sıkça kullanılır.

---

### 📝 **Sıfırlarla Dolu Tensör Oluşturma**

**`torch.zeros()`** fonksiyonunu kullanarak tamamen sıfırlarla dolu bir tensör oluşturabiliriz.


In [14]:
# (3, 4) boyutunda sıfırlardan oluşan bir tensör oluşturma
zeros = torch.zeros(size=(3, 4))

# Tensörü ve veri tipini yazdırma
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

### 🔢 Birlerle Dolu Tensör Oluşturma

Tıpkı sıfırlarla dolu bir tensör oluşturduğumuz gibi, **`torch.ones()`** fonksiyonunu kullanarak tüm elemanları **1** olan bir tensör oluşturabiliriz.  
Bu fonksiyon, belirli boyutlarda ve tüm değerleri **1** olan bir tensör oluşturur.


In [15]:
# (3, 4) boyutunda birlerden oluşan bir tensör oluşturma
ones = torch.ones(size=(3, 4))

# Tensörü ve veri tipini yazdırma
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### 🔢 **Belirli Bir Aralıkta Tensör Oluşturma (Range ve Benzersiz Tensörler)**

Bazen belirli bir sayı aralığında bir tensör oluşturmak isteyebilirsiniz.  
Örneğin, **1'den 10'a** veya **0'dan 100'e** kadar olan sayılar.

Bunu **`torch.arange(start, end, step)`** fonksiyonunu kullanarak yapabiliriz.

---

### ⚙️ **Parametreler:**

- **`start`** → Aralığın başlangıç değeri (örn. **0**)  
- **`end`** → Aralığın bitiş değeri (örn. **10**) *(bitiş değeri dahil değildir)*  
- **`step`** → Sayılar arasındaki artış miktarı (örn. **1**)

📌 **Not:**  
- Python'da **`range()`** fonksiyonunu kullanarak da sayı aralıkları oluşturabilirsiniz.  
- Ancak PyTorch'ta **`torch.range()`** fonksiyonu artık **kullanımdan kaldırılmıştır** ve ileride hata verebilir.  
  Bunun yerine **`torch.arange()`** kullanılmalıdır.


In [16]:
# ⚠️ Dikkat: torch.range() kullanımdan kaldırılmıştır (deprecated)
zero_to_ten_deprecated = torch.range(0, 10)  # Bu kullanım gelecekte hata verebilir!

# ✅ Doğru kullanım: torch.arange() ile 0'dan 10'a kadar bir tensör oluşturma
zero_to_ten = torch.arange(start=0, end=10, step=1)

# Tensörü yazdırma
zero_to_ten

<ipython-input-16-4ec072aa6a03>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)  # Bu kullanım gelecekte hata verebilir!


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 🔁 **Başka Bir Tensörle Aynı Şekilde Tensör Oluşturma**

Bazen mevcut bir tensörle **aynı boyutta** ancak farklı değerlerle (sıfır veya bir) doldurulmuş yeni bir tensör oluşturmak isteyebilirsiniz.  

Bu durumda, **`torch.zeros_like()`** ve **`torch.ones_like()`** fonksiyonlarını kullanabilirsiniz.  

- **`torch.zeros_like(input)`** → Verilen tensörle aynı boyutta, **sıfırlardan** oluşan bir tensör oluşturur.  
- **`torch.ones_like(input)`** → Verilen tensörle aynı boyutta, **birlerden** oluşan bir tensör oluşturur.  

---

In [17]:
# Mevcut bir tensörle aynı boyutta sıfırlardan oluşan bir tensör oluşturma
ten_zeros = torch.zeros_like(input=zero_to_ten)  # zero_to_ten ile aynı boyutta

# Oluşturulan tensörü yazdırma
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 🧩 **Tensör Veri Tipleri (Tensor Datatypes)**

PyTorch'ta birçok farklı **tensör veri tipi (datatype)** bulunmaktadır.  
Bu veri tiplerinin bazıları **CPU**, bazıları ise **GPU** için daha uygundur.

🔎 **Genel Bilgiler:**  
- **`torch.cuda`** kullanımı, tensörün **GPU**'da çalıştırıldığını gösterir.  
- En yaygın (ve varsayılan) veri tipi **`torch.float32`** veya **`torch.float`**’tir.  
- Bu tür, **32-bit kayan noktalı sayı (floating point)** olarak bilinir.

---

### 📊 **Farklı Veri Tipleri**

| **Veri Tipi**             | **Açıklama**                       | **Kısaltma**  |
|---------------------------|------------------------------------|---------------|
| **32-bit Float**          | Kayan noktalı sayı (varsayılan)    | `torch.float32` veya `torch.float` |
| **16-bit Float**          | Daha düşük hassasiyetli float      | `torch.float16` veya `torch.half`  |
| **64-bit Float**          | Daha yüksek hassasiyetli float     | `torch.float64` veya `torch.double` |
| **8, 16, 32, 64-bit Int** | Tam sayılar                       | `torch.int8`, `torch.int16`, `torch.int32`, `torch.int64` |

> **Not:**  
> - **Tam sayılar (integer):** Kesirli olmayan sayılar (örn. **7**)  
> - **Kayan noktalı sayılar (float):** Ondalıklı sayılar (örn. **7.0**)  

🔍 **Hassasiyet (Precision):**  
- **Düşük hassasiyet (8, 16-bit):** Daha hızlı işlem yapılır ancak doğruluk biraz düşebilir.  
- **Yüksek hassasiyet (32, 64-bit):** Daha fazla detay içerir ancak hesaplama süresi uzar.

---

In [18]:
#Belirli Veri Tipleriyle Tensör Oluşturma




# 32-bit float tensör (varsayılan)
float32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

# 16-bit float tensör
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# 64-bit float tensör
float64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

# 32-bit integer tensör
int32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

# Tensörleri yazdırma
print("32-bit Float Tensor:", float32_tensor)
print("16-bit Float Tensor:", float16_tensor)
print("64-bit Float Tensor:", float64_tensor)
print("32-bit Integer Tensor:", int32_tensor)

32-bit Float Tensor: tensor([1., 2., 3.])
16-bit Float Tensor: tensor([1., 2., 3.], dtype=torch.float16)
64-bit Float Tensor: tensor([1., 2., 3.], dtype=torch.float64)
32-bit Integer Tensor: tensor([1, 2, 3], dtype=torch.int32)


In [19]:
import torch

# Varsayılan olarak float32 tipinde bir tensör oluşturma
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,         # Belirtilmezse varsayılan olarak torch.float32 olur
                               device=None,        # Belirtilmezse CPU kullanılır
                               requires_grad=False)  # False olduğu için gradyan hesaplanmaz

# Tensörün şekli, veri tipi ve cihaz bilgisi
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

### ⚠️ **PyTorch'ta Yaygın Hatalar: Veri Tipi ve Cihaz Uyumsuzlukları**

PyTorch'ta karşılaşılan en yaygın hatalardan biri, **tensör şekli (shape)** uyuşmazlıklarıdır.  
Ancak bunun dışında iki önemli hata türü daha vardır:

1. **Veri Tipi (Datatype) Uyumsuzlukları:**  
   - Bir tensör **`torch.float32`**, diğeri **`torch.float16`** olduğunda uyumsuzluk oluşabilir.  
   - PyTorch, genellikle tensörlerin aynı veri tipinde olmasını ister.

2. **Cihaz (Device) Uyumsuzlukları:**  
   - Bir tensör **CPU** üzerinde, diğeri **GPU** üzerinde olduğunda hata verebilir.  
   - PyTorch, işlemlerin aynı cihazda yürütülmesini bekler.

📌 **Not:**  
- Tensörler arası hesaplamalarda **aynı veri tipi** ve **aynı cihazda** olmaları önemlidir.  
- İlerleyen konularda bu cihaz yönetimini daha detaylı inceleyeceğiz.

---

### 📝 **torch.float16 Veri Tipinde Tensör Oluşturma**

Şimdi, **`torch.float16`** veri tipinde bir tensör oluşturalım.  
**`torch.float16`**, daha düşük hassasiyetli ve daha hızlı hesaplamalar için kullanılır.


In [20]:
# 16-bit kayan noktalı (float16) tensör oluşturma
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)  # torch.half da kullanılabilir

# Tensörün veri tipini kontrol etme
float_16_tensor.dtype

torch.float16

## ℹ️ Tensörlerden Bilgi Alma

Tensörler oluşturduktan sonra (ister kendiniz, ister bir PyTorch modülü tarafından oluşturulmuş olsun), onlarla ilgili bazı bilgilere ihtiyaç duyabilirsiniz.

Daha önce de gördüğümüz gibi, tensörlerle ilgili en yaygın kullanılan üç özellik şunlardır:

- **`shape`** → Tensörün şekli nedir?  
  (*Bazı işlemler belirli şekil kurallarını gerektirir.*)  
- **`dtype`** → Tensördeki elemanlar hangi veri türünde saklanıyor?  
- **`device`** → Tensör hangi cihazda saklanıyor? (**CPU** veya **GPU**)

---

In [21]:
# 🔢 3x4 boyutunda rastgele bir tensör oluşturma
some_tensor = torch.rand(3, 4)

# ℹ️ Tensörün detaylarını yazdırma
print("Tensör:\n", some_tensor)
print(f"Tensörün Şekli (Shape): {some_tensor.shape}")
print(f"Tensörün Veri Tipi (Datatype): {some_tensor.dtype}")
print(f"Tensörün Cihazı (Device): {some_tensor.device}")  # Varsayılan olarak CPU'da tutulur


Tensör:
 tensor([[0.5015, 0.4369, 0.7028, 0.7865],
        [0.5677, 0.8335, 0.6876, 0.7213],
        [0.3433, 0.5446, 0.4910, 0.2284]])
Tensörün Şekli (Shape): torch.Size([3, 4])
Tensörün Veri Tipi (Datatype): torch.float32
Tensörün Cihazı (Device): cpu


> **📌 Not:**  
> PyTorch'ta karşılaştığınız hataların çoğu genellikle yukarıda bahsedilen **üç temel özellikten** biriyle ilgilidir:  
> - **Şekil (Shape)**  
> - **Veri Tipi (Datatype)**  
> - **Cihaz (Device)**  
>
> ❗ Hata mesajları aldığınızda, kendinize şu küçük şarkıyı söyleyin:  
>
> 🎵 *"Tensörlerimin şekli ne? Veri tipi ne ve nerede saklanıyorlar?  
> Şekil ne, veri tipi ne, nerede nerede nerede?"* 🎵  
>
> Bu üç soruyu kendinize sorarak sorunun kaynağını hızlıca bulabilirsiniz! 🔎


## 🔄 Tensörleri Manipüle Etme (Tensör Operasyonları)

Derin öğrenmede; **görseller**, **metinler**, **videolar**, **sesler**, hatta **protein yapıları** gibi veriler tensörler aracılığıyla temsil edilir.

📚 **Model nasıl öğrenir?**  
Bir model, bu tensörler üzerinde milyonlarca işlem yaparak verilerdeki kalıpları ve ilişkileri öğrenir.  
Bu işlemler, modelin girdileri daha iyi temsil etmesine yardımcı olur.

---

### 🎯 **Temel Tensör İşlemleri**

Derin öğrenmede kullanılan işlemler genellikle şu temel matematiksel işlemler etrafında döner:

- ➕ **Toplama (Addition)**  
- ➖ **Çıkarma (Subtraction)**  
- ✖️ **Çarpma (Element-wise Multiplication)**  
- ➗ **Bölme (Division)**  
- 🟰 **Matris Çarpımı (Matrix Multiplication)**

🔑 **Not:**  
Bu işlemler sinir ağlarının temel yapı taşlarını oluşturur.  
Bu yapı taşlarını doğru şekilde birleştirerek, **lego parçaları gibi** en karmaşık sinir ağlarını oluşturabilirsiniz! 🧩

---

### ➕ ➖ ✖️ **Temel Tensör İşlemleri (Basic Operations)**

Şimdi, en temel matematiksel işlemler olan **toplama (`+`)**, **çıkarma (`-`)** ve **çarpma (`*`)** işlemlerine bakalım.  
Bu işlemler, PyTorch'ta da tıpkı matematikte olduğu gibi çalışır.

---

In [22]:
# 🔢 Tensör oluşturma
tensor = torch.tensor([1, 2, 3])

# ➕ Tensöre 10 ekleme (eleman bazlı)
tensor + 10

tensor([11, 12, 13])

In [23]:
# ✖️ Tensörü 10 ile çarpma (eleman bazlı)
tensor * 10

tensor([10, 20, 30])

📌 **Dikkat:**  
Yukarıdaki tensör değerlerinin **`tensor([110, 120, 130])`** olmadığını fark ettiniz mi?  
Bunun nedeni, tensörün içindeki değerlerin **yeniden atanmadıkça değişmemesidir**.


In [24]:
# Tensörler yeniden atanmadıkça değişmez
tensor

tensor([1, 2, 3])

### ➖ Bir Sayı Çıkaralım ve Bu Sefer `tensor` Değişkenini Yeniden Atayalım.


In [25]:
# Çıkarma işlemi ve yeniden atama
tensor = tensor - 10

# Güncellenmiş tensörü yazdırma
print(tensor)

tensor([-9, -8, -7])


In [26]:
#Toplama işlemi ve yeniden atama
tensor = tensor + 10

# Güncellenmiş tensörü yazdırma
print(tensor)

tensor([1, 2, 3])



markdown
Kodu kopyala
### 🛠️ **PyTorch'un Yerleşik Fonksiyonları**

PyTorch, temel işlemleri gerçekleştirmek için birçok **yerleşik (built-in)** fonksiyon sunar.  
Bu fonksiyonlar, tensörler üzerinde hızlı ve etkili bir şekilde işlem yapmayı sağlar.

---

### 🔢 **Temel Yerleşik Fonksiyonlar**

- **`torch.add()`** → **Toplama** işlemi yapar.  
- **`torch.sub()`** → **Çıkarma** işlemi yapar.  
- **`torch.mul()`** → **Çarpma** işlemi yapar.  
- **`torch.div()`** → **Bölme** işlemi yapar.  

---

In [27]:
# PyTorch fonksiyonlarını da kullanabilirsiniz
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [28]:
# Orijinal tensör hâlâ değişmedi
tensor

tensor([1, 2, 3])

Ancak, `torch.mul()` yerine `*` gibi operatör sembollerini kullanmak daha yaygındır.


In [29]:
# 🔢 Eleman Bazlı Çarpma (Her eleman aynı indeksdeki elemanla çarpılır: 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Sonuç:", tensor * tensor)


tensor([1, 2, 3]) * tensor([1, 2, 3])
Sonuç: tensor([1, 4, 9])


### 🟰 **Matris Çarpımı (Matrix Multiplication)**

Makine öğrenimi ve derin öğrenme algoritmalarında (özellikle **sinir ağlarında**) en yaygın kullanılan işlemlerden biri **matris çarpımıdır**.  
PyTorch, matris çarpımı işlemini **[`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html)** fonksiyonuyla gerçekleştirir.

---

### 📏 **Matris Çarpımı için Temel Kurallar**

1. **İç Boyutlar Uyuşmalı (Inner Dimensions Must Match):**  
   - `(3, 2) @ (3, 2)` ❌ **Uyumsuz**  
   - `(2, 3) @ (3, 2)` ✅ **Uyumlu**  
   - `(3, 2) @ (2, 3)` ✅ **Uyumlu**

2. **Çıktının Boyutu Dış Boyutlardan Gelir (Resulting Shape = Outer Dimensions):**  
   - `(2, 3) @ (3, 2)` → **`(2, 2)`**  
   - `(3, 2) @ (2, 3)` → **`(3, 3)`**

> **📌 Not:**  
> Python'da **`@`** operatörü, **matris çarpımı** için kullanılır.

> **📚 Kaynak:**  
> Tüm matris çarpımı kurallarını görmek için [PyTorch dokümantasyonuna](https://pytorch.org/docs/stable/generated/torch.matmul.html) göz atabilirsiniz.

---

In [30]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

### 🔎 **Eleman Bazlı Çarpma ile Matris Çarpımı Arasındaki Fark**

**Eleman bazlı çarpma (element-wise multiplication)** ve **matris çarpımı (matrix multiplication)** arasındaki temel fark, **toplama işleminin** varlığıdır.

**`tensor`** değişkenimiz **`[1, 2, 3]`** değerlerine sahiptir.

| **İşlem**                       | **Hesaplama**                   | **Kod**                    |
|---------------------------------|--------------------------------|---------------------------|
| **➗ Eleman Bazlı Çarpma**      | `[1*1, 2*2, 3*3]` → `[1, 4, 9]` | `tensor * tensor`         |
| **🟰 Matris Çarpımı**           | `1*1 + 2*2 + 3*3` → `[14]`      | `tensor.matmul(tensor)`   |

---

In [31]:
# ➗ Eleman Bazlı Çarpma (Element-wise Multiplication)
tensor * tensor

tensor([1, 4, 9])

In [32]:
#matris çarpımı (matrix multiplication)
torch.matmul(tensor, tensor)

tensor(14)

In [33]:
# Matris çarpımı için "@" sembolü de kullanılabilir, ancak önerilmez.
tensor @ tensor


tensor(14)

Elle matris çarpımı yapabilirsiniz ancak bu önerilmez.

Yerleşik **`torch.matmul()`** yöntemi çok daha hızlıdır.


In [34]:
%%time
# 🟰 Elle Matris Çarpımı (Manuel Hesaplama)
# ❗ For döngüleriyle işlem yapmaktan kaçının, çünkü hesaplama maliyeti yüksektir!

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

# Sonucu yazdırma
value

CPU times: user 3.22 ms, sys: 1.74 ms, total: 4.96 ms
Wall time: 15.7 ms


tensor(14)

In [35]:
%%time
# 🟰 Matris Çarpımı - PyTorch Yerleşik Fonksiyonu ile
torch.matmul(tensor, tensor)

CPU times: user 100 µs, sys: 0 ns, total: 100 µs
Wall time: 105 µs


tensor(14)

## Derin Öğrenmede En Yaygın Hatalardan Biri (Şekil Hataları)

Derin öğrenmede yapılan işlemlerin çoğu matrislerin çarpılması ve üzerinde çeşitli işlemler yapılmasıdır.  
Matrisler, hangi şekil ve boyutlarda birleştirilebileceği konusunda katı kurallara sahiptir.  
Bu nedenle, derin öğrenmede en sık karşılaşılan hatalardan biri **şekil uyumsuzluklarıdır (shape mismatches)**.
### 📏 **Matris Çarpımı Kuralları**

1. **İç Boyutların Uyuşması Gerekir (Inner Dimensions Must Match):**  
   - `(3, 2) @ (3, 2)` ❌ **Uyumsuz**  
   - `(2, 3) @ (3, 2)` ✅ **Uyumlu**

2. **Çıktı Matrisinin Şekli Dış Boyutlardan Gelir:**  
   - `(2, 3) @ (3, 2)` → **`(2, 2)`**  
   - `(3, 2) @ (2, 3)` → **`(3, 3)`**

---


In [37]:
# 🔢 İki tensör oluşturuluyor
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# 🟰 Matris çarpımı (Bu işlem hata verecek!)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## 🟰 **Matris Çarpımını Uyumlu Hale Getirme (Transpose ile)**

**`tensor_A`** ve **`tensor_B`** arasında matris çarpımını gerçekleştirebilmek için, **iç boyutların (inner dimensions)** uyumlu olması gerekir.

### 🔄 **Bu Uyumu Sağlamanın Yollarından Biri: Transpoz (Transpose)**

**Transpoz**, bir tensörün **satır ve sütunlarını** yer değiştirerek boyutlarını çevirir.

### 🔧 **PyTorch'ta Transpoz Nasıl Yapılır?**

1. **`torch.transpose(input, dim0, dim1)`**  
   - `input`: Transpoz yapılacak tensör.  
   - `dim0` ve `dim1`: Yer değiştirecek boyutlar.

2. **`tensor.T`**  
   - Daha kısa ve pratik bir yöntemdir.  
   - Tensörün boyutlarını otomatik olarak yer değiştirir.

---

In [38]:
# tensor_A ve tensor_B'yi görüntüle
print(tensor_A)
print(tensor_B)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [39]:
# tensor_A ve tensor_B.T'yi görüntüle
print(tensor_A)
print(tensor_B.T)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [40]:
# tensor_B transpozu alındığında işlem çalışır
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")

# Matris çarpımını yap
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### 🛠️ **`torch.mm()` Kullanımı**

**`torch.mm()`** fonksiyonu, **`torch.matmul()`** fonksiyonunun kısaltmasıdır.  
Her ikisi de **matris çarpımı** için kullanılır ve aynı işlevi yerine getirir.


In [41]:
# torch.mm, matmul için bir kısaltmadır
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Şekil transpozunu almadan matris çarpımı yapmaya çalıştığımızda, matris çarpımının kuralları yerine getirilmez ve yukarıdaki gibi bir hata alırız.

Peki ya görsel bir örnek?

![Matris Çarpımının Görsel Gösterimi](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

Bu tür matris çarpımı görsellerini **[matrixmultiplication.xyz](http://matrixmultiplication.xyz/)** adresinde kendiniz oluşturabilirsiniz.

> **Not:**  
> Böyle bir matris çarpımı, aynı zamanda [**dot product** (nokta çarpımı)](https://www.mathsisfun.com/algebra/vectors-dot-product.html) olarak da adlandırılır.


Sinir ağları, matris çarpımları ve nokta çarpımlarıyla doludur.

**`torch.nn.Linear()`** modülü (bunu ilerleyen bölümlerde göreceğiz), aynı zamanda **feed-forward layer** veya **tam bağlantılı katman** olarak bilinir, bir giriş **`x`** ve ağırlıklar matris **`A`** arasında matris çarpımı gerçekleştirir.

$$
y = x\cdot{A^T} + b
$$

### Nerede:
- **`x`** katmana verilen giriştir (derin öğrenme, `torch.nn.Linear()` gibi katmanların üst üste konmasıyla oluşur).
- **`A`** katman tarafından oluşturulan ağırlıklar matrisidir, bu başlangıçta rastgele sayılarla başlar ve sinir ağı, verilerdeki kalıpları daha iyi temsil etmeyi öğrenirken bu sayılar ayarlanır (not edin, "`T`" burada ağırlıklar matrisinin transpoz edildiğini gösterir).
  - **Not:** Ağırlıklar matrisini **`W`** veya **`X`** gibi başka harflerle de görebilirsiniz.
- **`b`** ağırlıklar ve girişler arasında küçük bir kayma yaratmak için kullanılan bias terimidir.
- **`y`** çıkıştır (girişin bir manipülasyonu, amacı içerisindeki kalıpları keşfetmektir).

Bu bir doğrusal fonksiyondur (belki lise veya başka bir yerde **`y = mx+b`** gibi bir şey görmüşsünüzdür) ve doğrusal bir çizgi çizmeyi sağlar!

Şimdi bir doğrusal katmanla oynayalım.

Aşağıdaki **`in_features`** ve **`out_features`** değerlerini değiştirin ve ne olduğunu görün.

**Şekillerle** ilgili bir şey fark ediyor musunuz?


In [42]:
# 🔢 Rasgele ağırlıklar matrisinin tekrarlanabilir olmasını sağlamak için manuel tohum belirleme
torch.manual_seed(42)

# 🟰 Doğrusal katmanı oluşturma
linear = torch.nn.Linear(in_features=2,  # in_features = girişin iç boyutuyla uyumlu
                         out_features=6)  # out_features = dış boyutunu tanımlar

# 🧑‍💻 Giriş tensörünü tanımlama
x = tensor_A

# 🔄 Çıkışı hesaplama
output = linear(x)

# Sonuçları yazdırma
print(f"Giriş şekli: {x.shape}\n")
print(f"Çıktı:\n{output}\n\nÇıktı şekli: {output.shape}")

Giriş şekli: torch.Size([3, 2])

Çıktı:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Çıktı şekli: torch.Size([3, 6])


> **Soru:**  
> Yukarıdaki örnekte **`in_features`** değerini **2**'den **3**'e değiştirirseniz ne olur? Hata alır mısınız? Girişin (**`x`**) şeklinin hatayı karşılayabilmesi için nasıl değiştirilebilir? İpucu: Daha önce **`tensor_B`**'yi ne yapmak zorunda kaldık?


Eğer daha önce yapmadıysanız, matris çarpımı başlangıçta kafa karıştırıcı bir konu olabilir.

Ancak bir kaç kez denedikten ve birkaç sinir ağına göz attıktan sonra, her yerde olduğunu fark edeceksiniz.

Unutmayın, matris çarpımı **hemen her şey** için gereklidir.

![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*Sinir ağı katmanlarına girmeye ve kendi katmanlarınızı inşa etmeye başladığınızda, matris çarpımlarının her yerde olduğunu göreceksiniz. **Kaynak:** https://marksaroufim.substack.com/p/working-class-deep-learner*


### Min, max, mean, sum gibi işlemlerle toplama (aggregation)

Şimdi tensörleri nasıl manipüle edebileceğimizi gördük, şimdi de bunları **toplayarak** (daha fazla değerden daha az değere) nasıl işlem yapabileceğimizi görelim.

Önce bir tensör oluşturacağız ve ardından bu tensörün **max**, **min**, **mean** ve **sum** gibi değerlerini bulacağız.



In [43]:
# 🔢 Bir tensör oluşturma
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


Now let's perform some aggregation.

In [44]:
# Minimum değeri yazdırma
print(f"Minimum: {x.min()}")

# Maksimum değeri yazdırma
print(f"Maximum: {x.max()}")

# Ortalamayı yazdırma (Hata alır çünkü integer tensörde mean kullanılamaz)
# print(f"Mean: {x.mean()}") # Bu hata verir

# Ortalamayı doğru şekilde yazdırma (float32 veri tipi ile)
print(f"Mean: {x.type(torch.float32).mean()}") # float32 veri tipi ile çalışır

# Toplam değeri yazdırma
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **Not:**  
> Bazı yöntemlerin, örneğin **`torch.mean()`**, tensörlerin **`torch.float32`** (en yaygın) veya başka bir özel veri tipinde olmasını gerektirdiğini görebilirsiniz, aksi takdirde işlem başarısız olur.

Aşağıda yapmış olduğumuz işlemi **`torch`** yöntemleriyle de gerçekleştirebilirsiniz.


In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### **Pozisyonel Min/Max**

Bir tensörde maksimum veya minimum değerin bulunduğu **indeksi** bulmak için sırasıyla **`torch.argmax()`** ve **`torch.argmin()`** fonksiyonlarını kullanabilirsiniz.

Bu, **en yüksek (veya en düşük) değerin** pozisyonunu bilmek istediğinizde faydalıdır, ancak **değerin kendisini** değil. (Bunu, [softmax aktivasyon fonksiyonunu](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html) kullandığımız ilerleyen bölümlerde göreceğiz).

---

In [46]:
# 🔢 Tensör oluşturma
tensor = torch.arange(10, 100, 10)
print(f"Tensör: {tensor}")

# Maksimum ve minimum değerlerin indekslerini döndürme
print(f"Max değerin bulunduğu indeks: {tensor.argmax()}")
print(f"Min değerin bulunduğu indeks: {tensor.argmin()}")


Tensör: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Max değerin bulunduğu indeks: 8
Min değerin bulunduğu indeks: 0


### Tensör Veri Tipini Değiştirme

Daha önce de belirtildiği gibi, derin öğrenme işlemlerinde karşılaşılan yaygın sorunlardan biri, tensörlerin farklı veri tiplerinde olmasıdır.

Eğer bir tensör **`torch.float64`** tipindeyse ve diğer tensör **`torch.float32`** tipindeyse, bazı hatalarla karşılaşabilirsiniz.

Ama bunun bir çözümü var.

Tensörlerin veri tiplerini **[`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html)** fonksiyonunu kullanarak değiştirebilirsiniz. Burada **`dtype`** parametresi, kullanmak istediğiniz veri tipini belirtir.

Önce bir tensör oluşturacağız ve veri tipini kontrol edeceğiz (varsayılan olarak **`torch.float32`** olacaktır).


In [47]:
# 🔢 Tensör oluşturma ve veri tipini kontrol etme
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)


torch.float32


Şimdi, önceki tensörle aynı olan bir tensör oluşturacağız ancak veri tipini **`torch.float16`** olarak değiştireceğiz.


In [48]:
# 🔢 float16 veri tipiyle bir tensör oluşturma
tensor_float16 = tensor.type(torch.float16)
print(tensor_float16)


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)


Ve benzer şekilde, bir **`torch.int8`** tensörü oluşturmak için aynı işlemi yapabiliriz.


In [49]:
# 🔢 int8 veri tipiyle bir tensör oluşturma
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


> **Not:**  
> Farklı veri tipleri başlangıçta kafa karıştırıcı olabilir. Ama bunu şöyle düşünün, sayı ne kadar küçükse (örneğin **32**, **16**, **8**), bilgisayar değeri o kadar az hassasiyetle depolar. Ve daha az depolama ile, bu genellikle daha hızlı hesaplama ve daha küçük bir modelle sonuçlanır. Mobil tabanlı sinir ağları genellikle **8-bit tamsayılarla** çalışır; bunlar daha küçük ve hızlı çalışır, ancak **float32** karşılıklarına göre daha az doğruluk sağlar. Bu konuda daha fazla bilgi için **[hesaplamadaki hassasiyet](https://en.wikipedia.org/wiki/Precision_(computer_science))** hakkında okumayı öneririm.

> **Alıştırma:**  
> Şimdiye kadar pek çok tensör metodunu inceledik, ancak [`torch.Tensor` dokümantasyonunda](https://pytorch.org/docs/stable/tensors.html) daha pek çok metod var. 10 dakika ayırıp bu dokümantasyonu gözden geçirmenizi öneririm. İlginizi çekenleri tıklayıp, ardından kendi kodunuzla yazıp neler olduğunu görmek faydalı olacaktır.


### Yeniden Şekillendirme, Yığıt Oluşturma, Sıkıştırma ve Unsqueeze

Çoğu zaman, tensörlerinizin içindeki değerleri değiştirmeden boyutlarını yeniden şekillendirmek isteyeceksiniz.

Bunu yapmak için popüler yöntemler şunlardır:

| Yöntem | Kısa açıklama |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | `input`'ı `shape`'e yeniden şekillendirir (uyumluysa), ayrıca `torch.Tensor.reshape()` de kullanılabilir. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Orijinal tensörün aynı verileri paylaşarak farklı bir `shape`'teki görünümünü döndürür. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Bir dizi `tensör`ü yeni bir boyut (`dim`) boyunca birleştirir, tüm `tensörler` aynı boyutta olmalıdır. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | `input`'ı, değeri `1` olan tüm boyutları çıkararak sıkıştırır. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | `input`'ı, belirtilen `dim` boyutunda `1` değeri ekleyerek döndürür. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Orijinal `input`'ın boyutlarını `dims`'e göre sıralayarak döndüren *görünüm* sağlar. |

### Neden bunları yapmalısınız?

Çünkü derin öğrenme modelleri (sinir ağları), bir şekilde tensörleri manipüle etmekle ilgilidir. Ve matris çarpımı kuralları nedeniyle, şekil uyuşmazlıklarınız varsa, hatalarla karşılaşırsınız. Bu yöntemler, tensörlerinizin doğru elemanlarının diğer tensörlerin doğru elemanlarıyla karışmasını sağlamaya yardımcı olur.

Şimdi bunları deneyelim.

Önce bir tensör oluşturacağız.


In [50]:
# Tensör Oluşturma
import torch
x = torch.arange(1., 8.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Şimdi **`torch.reshape()`** ile ekstra bir boyut ekleyelim.


In [51]:
# Ekstra bir boyut ekleme
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Ayrıca görünümü **`torch.view()`** ile değiştirebiliriz.


In [52]:
# Görünümü değiştir (aynı veriyi korur ancak görünümü değiştirir)
# Daha fazla bilgi: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Ancak unutmayın, **`torch.view()`** ile bir tensörün görünümünü değiştirmek, aslında **aynı** tensörün yeni bir görünümünü oluşturur.

Yani görünümü değiştirmek, orijinal tensörü de değiştirir.


In [53]:
# z'yi değiştirmek x'i de değiştirir
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Eğer yeni tensörümüzü kendisinin üzerine beş kez yığmak istersek, bunu **`torch.stack()`** ile yapabiliriz.


In [54]:
# Tensörleri üst üste yığma
x_stacked = torch.stack([x, x, x, x], dim=0) # dim'i dim=1 olarak değiştirip ne olduğunu görün
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Ya bir tensörden tüm tek boyutları (single dimensions) kaldırmak istersek?

Bunu yapmak için **`torch.squeeze()`** kullanabilirsiniz (ben bunu, tensörü sadece 1'den büyük boyutlara sahip olacak şekilde **sıkıştırmak** olarak hatırlıyorum).


In [55]:
print(f"Önceki tensör: {x_reshaped}")
print(f"Önceki şekil: {x_reshaped.shape}")

# x_reshaped'ten ekstra boyutu kaldırma
x_squeezed = x_reshaped.squeeze()
print(f"\nYeni tensör: {x_squeezed}")
print(f"Yeni şekil: {x_squeezed.shape}")


Önceki tensör: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Önceki şekil: torch.Size([1, 7])

Yeni tensör: tensor([5., 2., 3., 4., 5., 6., 7.])
Yeni şekil: torch.Size([7])


Ve **`torch.squeeze()`**'in tersini yapmak için, belirli bir indekste **1** değeri eklemek için **`torch.unsqueeze()`** kullanabilirsiniz.


In [56]:
print(f"Önceki tensör: {x_squeezed}")
print(f"Önceki şekil: {x_squeezed.shape}")

## unsqueeze ile ekstra bir boyut ekleyin
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nYeni tensör: {x_unsqueezed}")
print(f"Yeni şekil: {x_unsqueezed.shape}")


Önceki tensör: tensor([5., 2., 3., 4., 5., 6., 7.])
Önceki şekil: torch.Size([7])

Yeni tensör: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Yeni şekil: torch.Size([1, 7])


Ayrıca **`torch.permute(input, dims)`** ile eksen değerlerinin sırasını yeniden düzenleyebilirsiniz; burada **`input`**, yeni **`dims`** ile bir *görünüm* haline gelir.


In [57]:
# Belirli bir şekle sahip tensör oluşturma
x_original = torch.rand(size=(224, 224, 3))

# Orijinal tensörü eksen sırasını yeniden düzenlemek için permute etme
x_permuted = x_original.permute(2, 0, 1) # eksenleri 0->1, 1->2, 2->0 şeklinde kaydırır

print(f"Önceki şekil: {x_original.shape}")
print(f"Yeni şekil: {x_permuted.shape}")


Önceki şekil: torch.Size([224, 224, 3])
Yeni şekil: torch.Size([3, 224, 224])


> **Not:**  
> Çünkü **`permute()`** bir *görünüm* döndürür (orijinal ile aynı veriyi paylaşır), permütelenmiş tensördeki değerler, orijinal tensörle aynı olacaktır ve eğer görünümdeki değerleri değiştirirseniz, bu orijinal tensörün değerlerini de değiştirir.


## İndeksleme (Tensörlerden veri seçme)

Bazen tensörlerden belirli verileri seçmek isteyebilirsiniz (örneğin, sadece ilk sütun veya ikinci satır gibi).

Bunu yapmak için indeksleme kullanabilirsiniz.

Eğer Python listelerinde veya NumPy dizilerinde indeksleme yaptıysanız, PyTorch'ta tensörlerle indeksleme yapmak oldukça benzer.


In [58]:
# Tensör oluşturma
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

İndeksleme işlemi dış boyuttan iç boyuta doğru yapılır (kare parantezlere göz atın).


In [59]:
# Hadi, parantez parantez indeksleyelim
print(f"İlk kare parantez:\n{x[0]}")
print(f"İkinci kare parantez: {x[0][0]}")
print(f"Üçüncü kare parantez: {x[0][0][0]}")


İlk kare parantez:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
İkinci kare parantez: tensor([1, 2, 3])
Üçüncü kare parantez: 1


Ayrıca **`:`** kullanarak "bu boyuttaki tüm değerleri" belirtebilir ve ardından bir virgül (**`,`**) kullanarak başka bir boyut ekleyebilirsiniz.


In [60]:
# 0. boyuttaki tüm değerleri ve 1. boyuttaki 0. indeksi almak
x[:, 0]


tensor([[1, 2, 3]])

In [61]:
# 0. ve 1. boyuttaki tüm değerleri, ancak yalnızca 2. boyuttaki 1. indeksi almak
x[:, :, 1]


tensor([[2, 5, 8]])

In [62]:
# 0. ve 1. boyutların 0. indeksini almak ve 2. boyuttaki tüm değerleri almak
x[0, 0, :] # x[0][0] ile aynı


tensor([1, 2, 3])

İndeksleme başta oldukça kafa karıştırıcı olabilir, özellikle daha büyük tensörlerle çalışırken (ben hâlâ doğru yapmak için birkaç kez indeksleme yapmam gerekiyor). Ama biraz pratik yaparak ve veri kaşiflerinin mottosunu takip ederek (***görselleştir, görselleştir, görselleştir***), zamanla alışmaya başlayacaksınız.


## PyTorch Tensörleri ve NumPy

NumPy, popüler bir Python sayısal hesaplama kütüphanesi olduğundan, PyTorch'un NumPy ile düzgün bir şekilde etkileşim kurma işlevselliği vardır.

NumPy ile PyTorch arasında (ve geriye) kullanmak isteyeceğiniz iki ana yöntem şunlardır:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy dizisi -> PyTorch tensörü.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensörü -> NumPy dizisi.

Şimdi bunları deneyelim.


In [63]:
# NumPy dizisini tensöre çevirme
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **Not:**  
> Varsayılan olarak, NumPy dizileri **`float64`** veri tipiyle oluşturulur ve PyTorch tensörüne dönüştürdüğünüzde aynı veri tipi korunur (yukarıdaki gibi).  
>  
> Ancak, birçok PyTorch hesaplaması varsayılan olarak **`float32`** kullanır.  
>  
> Yani, NumPy dizinizi (**`float64`**) -> PyTorch tensörü (**`float64`**) -> PyTorch tensörü (**`float32`**) olarak dönüştürmek istiyorsanız, **`tensor = torch.from_numpy(array).type(torch.float32)`** kullanabilirsiniz.  
>  
> Yukarıda **`tensor`**'u yeniden atadığımız için, tensörü değiştirdiğinizde dizi aynı kalır.


In [64]:
# Diziyi değiştir, tensörü aynı tut
array = array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Ve eğer PyTorch tensöründen NumPy dizisine geçmek isterseniz, **`tensor.numpy()`** fonksiyonunu çağırabilirsiniz.


In [65]:
# Tensörden NumPy dizisine
tensor = torch.ones(7) # float32 veri tipiyle bir tensör oluşturma
numpy_tensor = tensor.numpy() # dtype=float32 olacak, eğer değiştirilmezse
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Ve yukarıdaki kural aynen geçerlidir; eğer orijinal **`tensor`**'ı değiştirirseniz, yeni **`numpy_tensor`** aynı kalır.


In [66]:
# Tensörü değiştir, diziyi aynı tut
tensor = tensor + 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Tekrarlanabilirlik (Rastgeleliği Rastgelelikten Çıkarmaya Çalışmak)

Sinir ağları ve makine öğrenimi hakkında daha fazla şey öğrendikçe, rastgeleliğin ne kadar önemli bir rol oynadığını keşfedeceksiniz.

Aslında bu, **sahte rastgelelik**. Çünkü sonuçta, tasarlandıkları gibi bir bilgisayar temelde **deterministiktir** (her adım tahmin edilebilir), bu yüzden yarattıkları rastgelelikler, simüle edilmiş rastgeleliklerdir (bununla ilgili de tartışmalar olsa da, ben bir bilgisayar bilimci olmadığım için bunu kendiniz keşfetmenize bırakıyorum).

Peki bu, sinir ağları ve derin öğrenme ile nasıl ilişkilidir?

Sinir ağlarının, verilerdeki kalıpları tanımlamak için rastgele sayılarla başladığını ve bu sayıları tensör işlemleri (ve henüz tartışmadığımız birkaç başka şey) kullanarak iyileştirmeye çalıştığını konuştuk. Bu sayılar başlangıçta kötü tanımlamalardır ve verilerdeki kalıpları daha iyi tanımlamak için bu rastgele sayılar iyileştirilmeye çalışılır.

Kısacası:

``rastgele sayılarla başla -> tensör işlemleri -> daha iyi hale getirmeye çalış (defalarca ve tekrar)``

Rastgelelik güzel ve güçlü olsa da, bazen biraz daha az rastgelelik istersiniz.

Neden?

Çünkü tekrarlanabilir deneyler yapabilmek istersiniz.

Örneğin, X performansını elde edebilen bir algoritma oluşturursunuz.

Ve sonra arkadaşınız bunu deneyerek sizin deli olmadığınızı doğrulamak ister.

Bunu nasıl yapabilirler?

İşte burada **tekrarlanabilirlik** devreye giriyor.

Başka bir deyişle, aynı kodu çalıştıran bilgisayarımda aldığım aynı (veya çok benzer) sonuçları, sizin bilgisayarınızda alabilir misiniz?

Hadi PyTorch'ta tekrarlanabilirliğe kısa bir örnek bakalım.

İki rastgele tensör oluşturacağız. Çünkü rastgele olduklarından, farklı olmalarını beklersiniz, değil mi?


In [67]:
import torch

# İki rastgele tensör oluşturma
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensör A:\n{random_tensor_A}\n")
print(f"Tensör B:\n{random_tensor_B}\n")
print(f"Tensör A, Tensör B'ye eşit mi? (herhangi bir yerde)")
random_tensor_A == random_tensor_B


Tensör A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensör B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Tensör A, Tensör B'ye eşit mi? (herhangi bir yerde)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Beklediğiniz gibi, tensörler farklı değerlerle çıktı.

Ama ya iki rastgele tensörün *aynı* değerlere sahip olmasını isteseydiniz?

Yani tensörler hala rastgele değerlere sahip olacak ama aynı "lezzette" olacaklardı.

İşte burada **`torch.manual_seed(seed)`** devreye giriyor; burada **`seed`** bir tam sayıdır (mesela **`42`** olabilir ama başka bir şey de olabilir) ve rastgeleliği **lezzetlendiren** bir değerdir.

Hadi bunu deneyelim ve daha fazla *lezzetlendirilmiş* rastgele tensörler oluşturalım.


In [68]:
import torch
import random

# Rastgele tohum değerini ayarla
RANDOM_SEED = 42 # Bunu farklı değerlere değiştirerek aşağıdaki sayılarda ne olduğunu görebilirsiniz
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Her yeni rand() çağrıldığında tohumun sıfırlanması gerekir
# Bunu yapmazsanız, tensor_D, tensor_C'ye farklı olurdu
torch.random.manual_seed(seed=RANDOM_SEED) # Bu satırı yorum satırına almayı deneyin ve ne olacağını görün
random_tensor_D = torch.rand(3, 4)

print(f"Tensör C:\n{random_tensor_C}\n")
print(f"Tensör D:\n{random_tensor_D}\n")
print(f"Tensör C, Tensör D'ye eşit mi? (herhangi bir yerde)")
random_tensor_C == random_tensor_D


Tensör C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensör D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensör C, Tensör D'ye eşit mi? (herhangi bir yerde)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Harika!

Görünüşe göre tohum ayarlamak işe yaramış.

> **Kaynak:** Şu ana kadar ele aldıklarımız, PyTorch'ta tekrarlanabilirlik konusunda yalnızca yüzeyi çiziyor. Genel olarak tekrarlanabilirlik ve rastgele tohumlar hakkında daha fazla bilgi için şunları incelemenizi öneririm:
> * [PyTorch tekrarlanabilirlik dokümantasyonu](https://pytorch.org/docs/stable/notes/randomness.html) (iyi bir alıştırma, bunu 10 dakika boyunca okuyup anlamasanız da, buna aşina olmak önemlidir).
> * [Wikipedia rastgele tohum sayfası](https://en.wikipedia.org/wiki/Random_seed) (bu, rastgele tohumlar ve genel olarak sahte rastgelelik hakkında iyi bir genel bakış sağlar).


## Tensörleri GPU'larda Çalıştırma (ve Daha Hızlı Hesaplamalar Yapma)

Derin öğrenme algoritmaları çok fazla sayısal işlem gerektirir.

Ve varsayılan olarak bu işlemler çoğunlukla bir CPU'da (işlemci) yapılır.

Ancak, bir GPU (grafik işleme birimi) adında başka bir yaygın donanım türü vardır, bu donanım genellikle sinir ağlarının ihtiyaç duyduğu belirli türdeki işlemleri (matris çarpımları) CPU'lardan çok daha hızlı bir şekilde gerçekleştirebilir.

Bilgisayarınızda bir tane olabilir.

Eğer öyleyse, sinir ağlarını eğitmek için her fırsatta kullanmaya çalışmalısınız çünkü büyük ihtimalle eğitim süresini dramatik şekilde hızlandıracaktır.

GPU'ya erişmenin ve PyTorch'u GPU kullanacak şekilde yapılandırmanın birkaç yolu vardır.

> **Not:** Bu kurs boyunca "GPU"dan bahsederken, [CUDA etkinleştirilmiş bir Nvidia GPU'yu](https://developer.nvidia.com/cuda-gpus) kast ediyorum (CUDA, GPU'ların yalnızca grafik değil, genel amaçlı hesaplama için de kullanılmasını sağlayan bir hesaplama platformu ve API'sidir) aksi belirtilmedikçe.


### 1. GPU'ya Erişim

GPU dediğimde ne olduğunu zaten biliyor olabilirsiniz. Ancak bilmiyorsanız, birine erişim sağlamak için birkaç yol vardır.

| **Yöntem** | **Kurulum Zorluğu** | **Avantajlar** | **Dezavantajlar** | **Nasıl Kurulur** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Kolay | Ücretsiz, neredeyse sıfır kurulum gerektirir, çalışmaları başkalarıyla bir bağlantı kadar kolay paylaşabilirsiniz | Verilerinizi kaydetmez, sınırlı hesaplama gücü, zaman aşımına uğrayabilir | [Google Colab Kılavuzunu Takip Edin](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Kendi bilgisayarınızı kullanma | Orta | Her şeyi yerel olarak kendi bilgisayarınızda çalıştırabilirsiniz | GPU'lar ücretsiz değil, önceden maliyet gerektirir | [PyTorch kurulum yönergelerini takip edin](https://pytorch.org/get-started/locally/) |
| Bulut bilişim (AWS, GCP, Azure) | Orta-Zor | Küçük ön maliyet, neredeyse sonsuz hesaplama erişimi | Sürekli çalıştırırsanız pahalı olabilir, doğru şekilde kurmak zaman alabilir | [PyTorch bulut kurulum kılavuzunu takip edin](https://pytorch.org/get-started/cloud-partners/) |

GPU'ları kullanmak için daha fazla seçenek vardır ancak yukarıdaki üç seçenek şimdilik yeterli olacaktır.

Kişisel olarak, küçük ölçekli deneyler (ve bu kursu oluşturma) için Google Colab ve kendi bilgisayarımın bir kombinasyonunu kullanıyorum ve daha fazla hesaplama gücüne ihtiyaç duyduğumda bulut kaynaklarına başvuruyorum.

> **Kaynak:** Kendi GPU'nuzu satın almayı düşünüyorsanız ancak ne alacağınızı bilmiyorsanız, [Tim Dettmers'ın harika bir kılavuzu var](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

Bir Nvidia GPU'nuzun olup olmadığını kontrol etmek için, `!nvidia-smi` komutunu çalıştırabilirsiniz, burada `!` (aynı zamanda bang olarak da bilinir) "bunu komut satırında çalıştır" anlamına gelir.


In [69]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


Eğer erişebileceğiniz bir Nvidia GPU'nuz yoksa, yukarıdaki çıktı şu şekilde görünecektir:



### 2. PyTorch'u GPU üzerinde çalıştırma

Bir GPU'ya erişim sağladıktan sonra, bir sonraki adım, PyTorch'u verileri (tensörleri) depolamak ve veriler üzerinde hesaplamalar yapmak (tensörler üzerinde işlemler gerçekleştirmek) için kullanmaktır.

Bunu yapmak için **`torch.cuda`** paketini kullanabilirsiniz.

Bundan bahsetmek yerine, bunu deneyelim.

PyTorch'un bir GPU'ya erişimi olup olmadığını, **[`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available)** fonksiyonunu kullanarak test edebilirsiniz.


In [70]:
# GPU'yu kontrol etme
import torch
torch.cuda.is_available()


False

Eğer yukarıdaki çıktı **`True`** ise, PyTorch GPU'yu görebilir ve kullanabilir, eğer **`False`** çıkarsa, GPU'yu göremez ve bu durumda kurulum adımlarını tekrar gözden geçirmeniz gerekecek.

Şimdi, kodunuzu CPU *veya* mevcutsa GPU üzerinde çalışacak şekilde ayarlamak istediğinizi varsayalım.

Bu şekilde, siz veya birisi kodunuzu çalıştırmaya karar verdiğinde, kullandıkları hesaplama cihazına bakılmaksızın çalışacaktır.

Bir `device` değişkeni oluşturalım ve hangi tür cihazın mevcut olduğunu saklayalım.


In [71]:
# Cihaz türünü ayarlama
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cpu'

Yukarıdaki çıktı **`"cuda"`** ise, tüm PyTorch kodumuzu mevcut CUDA cihazını (GPU) kullanacak şekilde ayarlayabileceğimiz anlamına gelir ve eğer **`"cpu"`** çıkarsa, PyTorch kodumuz CPU üzerinde çalışacaktır.

> **Not:** PyTorch'ta, [**cihazdan bağımsız kod**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code) yazmak en iyi uygulamadır. Bu, CPU'da (her zaman mevcut) veya GPU'da (mevcutsa) çalışacak kod anlamına gelir.

Daha hızlı hesaplamalar yapmak istiyorsanız, bir GPU kullanabilirsiniz, ancak *çok* daha hızlı hesaplamalar yapmak istiyorsanız, birden fazla GPU kullanabilirsiniz.

PyTorch'un erişebileceği GPU sayısını, **[`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count)** fonksiyonunu kullanarak öğrenebilirsiniz.


In [72]:
# Cihaz sayısını sayma
torch.cuda.device_count()


0

PyTorch'un erişebileceği GPU sayısını bilmek, bir işlemi bir GPU'da ve başka bir işlemi diğer GPU'da çalıştırmak isterseniz faydalıdır (PyTorch ayrıca bir işlemi *tüm* GPU'lar üzerinde çalıştırmanıza olanak tanıyan özelliklere sahiptir).


### 2.1 PyTorch'u Apple Silicon'da Çalıştırma

Apple'ın M1/M2/M3 GPU'larında PyTorch çalıştırmak için **[`torch.backends.mps`](https://pytorch.org/docs/stable/notes/mps.html)** modülünü kullanabilirsiniz.

macOS ve PyTorch sürümlerinin güncel olduğundan emin olun.

PyTorch'un bir GPU'ya erişimi olup olmadığını **`torch.backends.mps.is_available()`** ile test edebilirsiniz.


In [73]:
# Apple Silicon GPU'yu kontrol etme
import torch
torch.backends.mps.is_available() # Not: Bu, bir Mac'te çalışmıyorsanız false döndürecektir


False

In [74]:
# Cihaz türünü ayarlama
device = "mps" if torch.backends.mps.is_available() else "cpu"
device


'cpu'

Yukarıdaki çıktı **`"mps"`** ise, tüm PyTorch kodumuzu mevcut Apple Silicon GPU'sunu kullanacak şekilde ayarlayabileceğimiz anlamına gelir.


In [75]:
if torch.cuda.is_available():
    device = "cuda"  # NVIDIA GPU'yu kullan (eğer mevcutsa)
elif torch.backends.mps.is_available():
    device = "mps"  # Apple Silicon GPU'yu kullan (eğer mevcutsa)
else:
    device = "cpu"  # GPU yoksa varsayılan olarak CPU kullan


### 3. Tensörleri (ve modelleri) GPU'ya koyma

Tensörleri (ve modelleri, bunu daha sonra göreceğiz) belirli bir cihaza koymak için onlara **`to(device)`** fonksiyonunu çağırabilirsiniz. Burada **`device`**, tensörün (veya modelin) gitmesini istediğiniz hedef cihazdır.

Bunu neden yapmalısınız?

GPU'lar, CPU'lardan çok daha hızlı sayısal hesaplamalar yapar ve eğer bir GPU mevcut değilse, **cihazdan bağımsız kodumuz** (yukarıya bakın) sayesinde kod CPU üzerinde çalışacaktır.

> **Not:** **`to(device)`** kullanarak bir tensörü GPU'ya koymak (örneğin **`some_tensor.to(device)`**) o tensörün bir kopyasını döndürür; örneğin, aynı tensör hem CPU'da hem de GPU'da olacaktır. Tensörleri üzerine yazmak için onları yeniden atayın:
>
> `some_tensor = some_tensor.to(device)`

Hadi, bir tensör oluşturalım ve onu GPU'ya koyalım (eğer mevcutsa).


In [76]:
# Tensör oluşturma (varsayılan olarak CPU üzerinde)
tensor = torch.tensor([1, 2, 3])

# Tensör GPU'da değil
print(tensor, tensor.device)

# Tensörü GPU'ya taşıma (eğer mevcutsa)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

Eğer bir GPU'nuz mevcutsa, yukarıdaki kod şu şekilde bir çıktı verecektir:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

İkinci tensörün **`device='cuda:0'`** olduğunu fark edin, bu, tensörün mevcut 0. GPU'da depolandığını gösterir (GPU'lar 0'dan başlar, eğer iki GPU mevcutsa, sırasıyla `'cuda:0'` ve `'cuda:1'` olur, bu şekilde `'cuda:n'`'e kadar devam eder).


### 4. Tensörleri CPU'ya geri taşıma

Ya tensörü geri CPU'ya taşımak istersek?

Örneğin, tensörlerinizle NumPy ile etkileşimde bulunmak isterseniz bunu yapmak isteyebilirsiniz (NumPy, GPU'yu kullanmaz).

Hadi, **`torch.Tensor.numpy()`** metodunu **`tensor_on_gpu`** üzerinde deneyelim.


In [77]:
# Eğer tensör GPU'daysa, NumPy'ye dönüştürülemez (bu hata verecektir)
tensor_on_gpu.numpy()


array([1, 2, 3])

Bunun yerine, bir tensörü CPU'ya geri almak ve NumPy ile kullanılabilir hale getirmek için **[`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html)** kullanabiliriz.

Bu, tensörü CPU belleğine kopyalar, böylece CPU'lar ile kullanılabilir hale gelir.


In [78]:
# Bunun yerine, tensörü geri CPU'ya kopyala
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

Yukarıdaki işlem, GPU tensörünün bir kopyasını CPU belleğine döndürür, böylece orijinal tensör hala GPU üzerinde kalır.


In [79]:
tensor_on_gpu

tensor([1, 2, 3])